# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import business_setting_pb2 as business__setting__pb2


class BusinessSettingStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.table = channel.unary_unary(
                '/BusinessSetting/table',
                request_serializer=business__setting__pb2.BusinessSettingTableRequest.SerializeToString,
                response_deserializer=business__setting__pb2.BusinessSettingTableResponse.FromString,
                )
        self.get_all = channel.unary_unary(
                '/BusinessSetting/get_all',
                request_serializer=business__setting__pb2.BusinessSettingEmpty.SerializeToString,
                response_deserializer=business__setting__pb2.BusinessSettingMultipleResponse.FromString,
                )
        self.get = channel.unary_unary(
                '/BusinessSetting/get',
                request_serializer=business__setting__pb2.BusinessSettingIdRequest.SerializeToString,
                response_deserializer=business__setting__pb2.BusinessSettingResponse.FromString,
                )
        self.save = channel.unary_unary(
                '/BusinessSetting/save',
                request_serializer=business__setting__pb2.BusinessSettingNotIdRequest.SerializeToString,
                response_deserializer=business__setting__pb2.BusinessSettingResponse.FromString,
                )
        self.update = channel.unary_unary(
                '/BusinessSetting/update',
                request_serializer=business__setting__pb2.BusinessSettingRequest.SerializeToString,
                response_deserializer=business__setting__pb2.BusinessSettingResponse.FromString,
                )
        self.delete = channel.unary_unary(
                '/BusinessSetting/delete',
                request_serializer=business__setting__pb2.BusinessSettingIdRequest.SerializeToString,
                response_deserializer=business__setting__pb2.BusinessSettingEmpty.FromString,
                )


class BusinessSettingServicer(object):
    """Missing associated documentation comment in .proto file."""

    def table(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_all(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def save(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BusinessSettingServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'table': grpc.unary_unary_rpc_method_handler(
                    servicer.table,
                    request_deserializer=business__setting__pb2.BusinessSettingTableRequest.FromString,
                    response_serializer=business__setting__pb2.BusinessSettingTableResponse.SerializeToString,
            ),
            'get_all': grpc.unary_unary_rpc_method_handler(
                    servicer.get_all,
                    request_deserializer=business__setting__pb2.BusinessSettingEmpty.FromString,
                    response_serializer=business__setting__pb2.BusinessSettingMultipleResponse.SerializeToString,
            ),
            'get': grpc.unary_unary_rpc_method_handler(
                    servicer.get,
                    request_deserializer=business__setting__pb2.BusinessSettingIdRequest.FromString,
                    response_serializer=business__setting__pb2.BusinessSettingResponse.SerializeToString,
            ),
            'save': grpc.unary_unary_rpc_method_handler(
                    servicer.save,
                    request_deserializer=business__setting__pb2.BusinessSettingNotIdRequest.FromString,
                    response_serializer=business__setting__pb2.BusinessSettingResponse.SerializeToString,
            ),
            'update': grpc.unary_unary_rpc_method_handler(
                    servicer.update,
                    request_deserializer=business__setting__pb2.BusinessSettingRequest.FromString,
                    response_serializer=business__setting__pb2.BusinessSettingResponse.SerializeToString,
            ),
            'delete': grpc.unary_unary_rpc_method_handler(
                    servicer.delete,
                    request_deserializer=business__setting__pb2.BusinessSettingIdRequest.FromString,
                    response_serializer=business__setting__pb2.BusinessSettingEmpty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'BusinessSetting', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class BusinessSetting(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def table(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/BusinessSetting/table',
            business__setting__pb2.BusinessSettingTableRequest.SerializeToString,
            business__setting__pb2.BusinessSettingTableResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def get_all(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/BusinessSetting/get_all',
            business__setting__pb2.BusinessSettingEmpty.SerializeToString,
            business__setting__pb2.BusinessSettingMultipleResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/BusinessSetting/get',
            business__setting__pb2.BusinessSettingIdRequest.SerializeToString,
            business__setting__pb2.BusinessSettingResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def save(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/BusinessSetting/save',
            business__setting__pb2.BusinessSettingNotIdRequest.SerializeToString,
            business__setting__pb2.BusinessSettingResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/BusinessSetting/update',
            business__setting__pb2.BusinessSettingRequest.SerializeToString,
            business__setting__pb2.BusinessSettingResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/BusinessSetting/delete',
            business__setting__pb2.BusinessSettingIdRequest.SerializeToString,
            business__setting__pb2.BusinessSettingEmpty.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
