# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: general_setting.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='general_setting.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x15general_setting.proto\"\x15\n\x13GeneralSettingEmpty\"%\n\x17GeneralSettingIdRequest\x12\n\n\x02id\x18\x01 \x02(\t\"T\n\x1aGeneralSettingNotIdRequest\x12\x13\n\x0bsessionTime\x18\x01 \x02(\x05\x12\x0b\n\x03\x61pp\x18\x02 \x02(\t\x12\x14\n\x0cmultiSession\x18\x03 \x02(\x08\"[\n\x15GeneralSettingRequest\x12\n\n\x02id\x18\x01 \x02(\t\x12\x13\n\x0bsessionTime\x18\x02 \x02(\x05\x12\x0b\n\x03\x61pp\x18\x03 \x02(\t\x12\x14\n\x0cmultiSession\x18\x04 \x02(\x08\"P\n\x1aGeneralSettingTableRequest\x12\x0c\n\x04page\x18\x01 \x02(\x05\x12\x14\n\x08per_page\x18\x02 \x01(\x05:\x02\x31\x35\x12\x0e\n\x06search\x18\x03 \x01(\t\"A\n\x16GeneralSettingResponse\x12\'\n\x07general\x18\x01 \x02(\x0b\x32\x16.GeneralSettingRequest\"I\n\x1eGeneralSettingMultipleResponse\x12\'\n\x07general\x18\x01 \x03(\x0b\x32\x16.GeneralSettingRequest\"\x8c\x01\n\x1bGeneralSettingTableResponse\x12%\n\x05items\x18\x01 \x03(\x0b\x32\x16.GeneralSettingRequest\x12\x0c\n\x04page\x18\x02 \x02(\x05\x12\x10\n\x08per_page\x18\x03 \x02(\x05\x12\x13\n\x0btotal_items\x18\x04 \x02(\x05\x12\x11\n\tnum_pages\x18\x05 \x02(\x05\x32\x83\x03\n\x0eGeneralSetting\x12\x42\n\x05table\x12\x1b.GeneralSettingTableRequest\x1a\x1c.GeneralSettingTableResponse\x12@\n\x07get_all\x12\x14.GeneralSettingEmpty\x1a\x1f.GeneralSettingMultipleResponse\x12\x38\n\x03get\x12\x18.GeneralSettingIdRequest\x1a\x17.GeneralSettingResponse\x12<\n\x04save\x12\x1b.GeneralSettingNotIdRequest\x1a\x17.GeneralSettingResponse\x12\x39\n\x06update\x12\x16.GeneralSettingRequest\x1a\x17.GeneralSettingResponse\x12\x38\n\x06\x64\x65lete\x12\x18.GeneralSettingIdRequest\x1a\x14.GeneralSettingEmpty'
)




_GENERALSETTINGEMPTY = _descriptor.Descriptor(
  name='GeneralSettingEmpty',
  full_name='GeneralSettingEmpty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=46,
)


_GENERALSETTINGIDREQUEST = _descriptor.Descriptor(
  name='GeneralSettingIdRequest',
  full_name='GeneralSettingIdRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='GeneralSettingIdRequest.id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=85,
)


_GENERALSETTINGNOTIDREQUEST = _descriptor.Descriptor(
  name='GeneralSettingNotIdRequest',
  full_name='GeneralSettingNotIdRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='sessionTime', full_name='GeneralSettingNotIdRequest.sessionTime', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='app', full_name='GeneralSettingNotIdRequest.app', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='multiSession', full_name='GeneralSettingNotIdRequest.multiSession', index=2,
      number=3, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=87,
  serialized_end=171,
)


_GENERALSETTINGREQUEST = _descriptor.Descriptor(
  name='GeneralSettingRequest',
  full_name='GeneralSettingRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='GeneralSettingRequest.id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sessionTime', full_name='GeneralSettingRequest.sessionTime', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='app', full_name='GeneralSettingRequest.app', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='multiSession', full_name='GeneralSettingRequest.multiSession', index=3,
      number=4, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=173,
  serialized_end=264,
)


_GENERALSETTINGTABLEREQUEST = _descriptor.Descriptor(
  name='GeneralSettingTableRequest',
  full_name='GeneralSettingTableRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='page', full_name='GeneralSettingTableRequest.page', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='per_page', full_name='GeneralSettingTableRequest.per_page', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=15,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='search', full_name='GeneralSettingTableRequest.search', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=266,
  serialized_end=346,
)


_GENERALSETTINGRESPONSE = _descriptor.Descriptor(
  name='GeneralSettingResponse',
  full_name='GeneralSettingResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='general', full_name='GeneralSettingResponse.general', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=348,
  serialized_end=413,
)


_GENERALSETTINGMULTIPLERESPONSE = _descriptor.Descriptor(
  name='GeneralSettingMultipleResponse',
  full_name='GeneralSettingMultipleResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='general', full_name='GeneralSettingMultipleResponse.general', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=415,
  serialized_end=488,
)


_GENERALSETTINGTABLERESPONSE = _descriptor.Descriptor(
  name='GeneralSettingTableResponse',
  full_name='GeneralSettingTableResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='items', full_name='GeneralSettingTableResponse.items', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='page', full_name='GeneralSettingTableResponse.page', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='per_page', full_name='GeneralSettingTableResponse.per_page', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='total_items', full_name='GeneralSettingTableResponse.total_items', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='num_pages', full_name='GeneralSettingTableResponse.num_pages', index=4,
      number=5, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=491,
  serialized_end=631,
)

_GENERALSETTINGRESPONSE.fields_by_name['general'].message_type = _GENERALSETTINGREQUEST
_GENERALSETTINGMULTIPLERESPONSE.fields_by_name['general'].message_type = _GENERALSETTINGREQUEST
_GENERALSETTINGTABLERESPONSE.fields_by_name['items'].message_type = _GENERALSETTINGREQUEST
DESCRIPTOR.message_types_by_name['GeneralSettingEmpty'] = _GENERALSETTINGEMPTY
DESCRIPTOR.message_types_by_name['GeneralSettingIdRequest'] = _GENERALSETTINGIDREQUEST
DESCRIPTOR.message_types_by_name['GeneralSettingNotIdRequest'] = _GENERALSETTINGNOTIDREQUEST
DESCRIPTOR.message_types_by_name['GeneralSettingRequest'] = _GENERALSETTINGREQUEST
DESCRIPTOR.message_types_by_name['GeneralSettingTableRequest'] = _GENERALSETTINGTABLEREQUEST
DESCRIPTOR.message_types_by_name['GeneralSettingResponse'] = _GENERALSETTINGRESPONSE
DESCRIPTOR.message_types_by_name['GeneralSettingMultipleResponse'] = _GENERALSETTINGMULTIPLERESPONSE
DESCRIPTOR.message_types_by_name['GeneralSettingTableResponse'] = _GENERALSETTINGTABLERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GeneralSettingEmpty = _reflection.GeneratedProtocolMessageType('GeneralSettingEmpty', (_message.Message,), {
  'DESCRIPTOR' : _GENERALSETTINGEMPTY,
  '__module__' : 'general_setting_pb2'
  # @@protoc_insertion_point(class_scope:GeneralSettingEmpty)
  })
_sym_db.RegisterMessage(GeneralSettingEmpty)

GeneralSettingIdRequest = _reflection.GeneratedProtocolMessageType('GeneralSettingIdRequest', (_message.Message,), {
  'DESCRIPTOR' : _GENERALSETTINGIDREQUEST,
  '__module__' : 'general_setting_pb2'
  # @@protoc_insertion_point(class_scope:GeneralSettingIdRequest)
  })
_sym_db.RegisterMessage(GeneralSettingIdRequest)

GeneralSettingNotIdRequest = _reflection.GeneratedProtocolMessageType('GeneralSettingNotIdRequest', (_message.Message,), {
  'DESCRIPTOR' : _GENERALSETTINGNOTIDREQUEST,
  '__module__' : 'general_setting_pb2'
  # @@protoc_insertion_point(class_scope:GeneralSettingNotIdRequest)
  })
_sym_db.RegisterMessage(GeneralSettingNotIdRequest)

GeneralSettingRequest = _reflection.GeneratedProtocolMessageType('GeneralSettingRequest', (_message.Message,), {
  'DESCRIPTOR' : _GENERALSETTINGREQUEST,
  '__module__' : 'general_setting_pb2'
  # @@protoc_insertion_point(class_scope:GeneralSettingRequest)
  })
_sym_db.RegisterMessage(GeneralSettingRequest)

GeneralSettingTableRequest = _reflection.GeneratedProtocolMessageType('GeneralSettingTableRequest', (_message.Message,), {
  'DESCRIPTOR' : _GENERALSETTINGTABLEREQUEST,
  '__module__' : 'general_setting_pb2'
  # @@protoc_insertion_point(class_scope:GeneralSettingTableRequest)
  })
_sym_db.RegisterMessage(GeneralSettingTableRequest)

GeneralSettingResponse = _reflection.GeneratedProtocolMessageType('GeneralSettingResponse', (_message.Message,), {
  'DESCRIPTOR' : _GENERALSETTINGRESPONSE,
  '__module__' : 'general_setting_pb2'
  # @@protoc_insertion_point(class_scope:GeneralSettingResponse)
  })
_sym_db.RegisterMessage(GeneralSettingResponse)

GeneralSettingMultipleResponse = _reflection.GeneratedProtocolMessageType('GeneralSettingMultipleResponse', (_message.Message,), {
  'DESCRIPTOR' : _GENERALSETTINGMULTIPLERESPONSE,
  '__module__' : 'general_setting_pb2'
  # @@protoc_insertion_point(class_scope:GeneralSettingMultipleResponse)
  })
_sym_db.RegisterMessage(GeneralSettingMultipleResponse)

GeneralSettingTableResponse = _reflection.GeneratedProtocolMessageType('GeneralSettingTableResponse', (_message.Message,), {
  'DESCRIPTOR' : _GENERALSETTINGTABLERESPONSE,
  '__module__' : 'general_setting_pb2'
  # @@protoc_insertion_point(class_scope:GeneralSettingTableResponse)
  })
_sym_db.RegisterMessage(GeneralSettingTableResponse)



_GENERALSETTING = _descriptor.ServiceDescriptor(
  name='GeneralSetting',
  full_name='GeneralSetting',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=634,
  serialized_end=1021,
  methods=[
  _descriptor.MethodDescriptor(
    name='table',
    full_name='GeneralSetting.table',
    index=0,
    containing_service=None,
    input_type=_GENERALSETTINGTABLEREQUEST,
    output_type=_GENERALSETTINGTABLERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='get_all',
    full_name='GeneralSetting.get_all',
    index=1,
    containing_service=None,
    input_type=_GENERALSETTINGEMPTY,
    output_type=_GENERALSETTINGMULTIPLERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='get',
    full_name='GeneralSetting.get',
    index=2,
    containing_service=None,
    input_type=_GENERALSETTINGIDREQUEST,
    output_type=_GENERALSETTINGRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='save',
    full_name='GeneralSetting.save',
    index=3,
    containing_service=None,
    input_type=_GENERALSETTINGNOTIDREQUEST,
    output_type=_GENERALSETTINGRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='update',
    full_name='GeneralSetting.update',
    index=4,
    containing_service=None,
    input_type=_GENERALSETTINGREQUEST,
    output_type=_GENERALSETTINGRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='delete',
    full_name='GeneralSetting.delete',
    index=5,
    containing_service=None,
    input_type=_GENERALSETTINGIDREQUEST,
    output_type=_GENERALSETTINGEMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_GENERALSETTING)

DESCRIPTOR.services_by_name['GeneralSetting'] = _GENERALSETTING

# @@protoc_insertion_point(module_scope)
