# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import session_pb2 as session__pb2


class SessionStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.table = channel.unary_unary(
                '/Session/table',
                request_serializer=session__pb2.SessionTableRequest.SerializeToString,
                response_deserializer=session__pb2.SessionTableResponse.FromString,
                )
        self.get_all = channel.unary_unary(
                '/Session/get_all',
                request_serializer=session__pb2.SessionEmpty.SerializeToString,
                response_deserializer=session__pb2.SessionMultipleResponse.FromString,
                )
        self.get = channel.unary_unary(
                '/Session/get',
                request_serializer=session__pb2.SessionOneRequest.SerializeToString,
                response_deserializer=session__pb2.SessionResponse.FromString,
                )
        self.save = channel.unary_unary(
                '/Session/save',
                request_serializer=session__pb2.SessionNotIdRequest.SerializeToString,
                response_deserializer=session__pb2.SessionResponse.FromString,
                )
        self.update = channel.unary_unary(
                '/Session/update',
                request_serializer=session__pb2.SessionRequest.SerializeToString,
                response_deserializer=session__pb2.SessionResponse.FromString,
                )
        self.delete = channel.unary_unary(
                '/Session/delete',
                request_serializer=session__pb2.SessionIdRequest.SerializeToString,
                response_deserializer=session__pb2.SessionEmpty.FromString,
                )


class SessionServicer(object):
    """Missing associated documentation comment in .proto file."""

    def table(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_all(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def save(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SessionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'table': grpc.unary_unary_rpc_method_handler(
                    servicer.table,
                    request_deserializer=session__pb2.SessionTableRequest.FromString,
                    response_serializer=session__pb2.SessionTableResponse.SerializeToString,
            ),
            'get_all': grpc.unary_unary_rpc_method_handler(
                    servicer.get_all,
                    request_deserializer=session__pb2.SessionEmpty.FromString,
                    response_serializer=session__pb2.SessionMultipleResponse.SerializeToString,
            ),
            'get': grpc.unary_unary_rpc_method_handler(
                    servicer.get,
                    request_deserializer=session__pb2.SessionOneRequest.FromString,
                    response_serializer=session__pb2.SessionResponse.SerializeToString,
            ),
            'save': grpc.unary_unary_rpc_method_handler(
                    servicer.save,
                    request_deserializer=session__pb2.SessionNotIdRequest.FromString,
                    response_serializer=session__pb2.SessionResponse.SerializeToString,
            ),
            'update': grpc.unary_unary_rpc_method_handler(
                    servicer.update,
                    request_deserializer=session__pb2.SessionRequest.FromString,
                    response_serializer=session__pb2.SessionResponse.SerializeToString,
            ),
            'delete': grpc.unary_unary_rpc_method_handler(
                    servicer.delete,
                    request_deserializer=session__pb2.SessionIdRequest.FromString,
                    response_serializer=session__pb2.SessionEmpty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Session', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Session(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def table(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Session/table',
            session__pb2.SessionTableRequest.SerializeToString,
            session__pb2.SessionTableResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def get_all(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Session/get_all',
            session__pb2.SessionEmpty.SerializeToString,
            session__pb2.SessionMultipleResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Session/get',
            session__pb2.SessionOneRequest.SerializeToString,
            session__pb2.SessionResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def save(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Session/save',
            session__pb2.SessionNotIdRequest.SerializeToString,
            session__pb2.SessionResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Session/update',
            session__pb2.SessionRequest.SerializeToString,
            session__pb2.SessionResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Session/delete',
            session__pb2.SessionIdRequest.SerializeToString,
            session__pb2.SessionEmpty.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
