# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: credit_cards.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='credit_cards.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12\x63redit_cards.proto\"\x11\n\x0f\x43reditCardEmpty\"!\n\x13\x43reditCardIdRequest\x12\n\n\x02id\x18\x01 \x02(\t\"h\n\x16\x43reditCardNotIdRequest\x12\x0e\n\x06\x65ntity\x18\x01 \x02(\t\x12\x15\n\rcvcValidation\x18\x02 \x02(\x05\x12\x18\n\x10numberValidation\x18\x03 \x02(\x05\x12\r\n\x05regex\x18\x04 \x02(\t\"o\n\x11\x43reditCardRequest\x12\n\n\x02id\x18\x01 \x02(\t\x12\x0e\n\x06\x65ntity\x18\x02 \x02(\t\x12\x15\n\rcvcValidation\x18\x03 \x02(\x05\x12\x18\n\x10numberValidation\x18\x04 \x02(\x05\x12\r\n\x05regex\x18\x05 \x02(\t\"L\n\x16\x43reditCardTableRequest\x12\x0c\n\x04page\x18\x01 \x02(\x05\x12\x14\n\x08per_page\x18\x02 \x01(\x05:\x02\x31\x35\x12\x0e\n\x06search\x18\x03 \x01(\t\"9\n\x13\x43reditCardsResponse\x12\"\n\x06\x63redit\x18\x01 \x02(\x0b\x32\x12.CreditCardRequest\"A\n\x1b\x43reditCardsMultipleResponse\x12\"\n\x06\x63redit\x18\x01 \x03(\x0b\x32\x12.CreditCardRequest\"\x85\x01\n\x18\x43reditCardsTableResponse\x12!\n\x05items\x18\x01 \x03(\x0b\x32\x12.CreditCardRequest\x12\x0c\n\x04page\x18\x02 \x02(\x05\x12\x10\n\x08per_page\x18\x03 \x02(\x05\x12\x13\n\x0btotal_items\x18\x04 \x02(\x05\x12\x11\n\tnum_pages\x18\x05 \x02(\x05\x32\xd9\x02\n\x0b\x43reditCards\x12;\n\x05table\x12\x17.CreditCardTableRequest\x1a\x19.CreditCardsTableResponse\x12\x39\n\x07get_all\x12\x10.CreditCardEmpty\x1a\x1c.CreditCardsMultipleResponse\x12\x31\n\x03get\x12\x14.CreditCardIdRequest\x1a\x14.CreditCardsResponse\x12\x35\n\x04save\x12\x17.CreditCardNotIdRequest\x1a\x14.CreditCardsResponse\x12\x32\n\x06update\x12\x12.CreditCardRequest\x1a\x14.CreditCardsResponse\x12\x34\n\x06\x64\x65lete\x12\x14.CreditCardIdRequest\x1a\x14.CreditCardsResponse'
)




_CREDITCARDEMPTY = _descriptor.Descriptor(
  name='CreditCardEmpty',
  full_name='CreditCardEmpty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=39,
)


_CREDITCARDIDREQUEST = _descriptor.Descriptor(
  name='CreditCardIdRequest',
  full_name='CreditCardIdRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='CreditCardIdRequest.id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=74,
)


_CREDITCARDNOTIDREQUEST = _descriptor.Descriptor(
  name='CreditCardNotIdRequest',
  full_name='CreditCardNotIdRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='entity', full_name='CreditCardNotIdRequest.entity', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cvcValidation', full_name='CreditCardNotIdRequest.cvcValidation', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='numberValidation', full_name='CreditCardNotIdRequest.numberValidation', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='regex', full_name='CreditCardNotIdRequest.regex', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=76,
  serialized_end=180,
)


_CREDITCARDREQUEST = _descriptor.Descriptor(
  name='CreditCardRequest',
  full_name='CreditCardRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='CreditCardRequest.id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='entity', full_name='CreditCardRequest.entity', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cvcValidation', full_name='CreditCardRequest.cvcValidation', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='numberValidation', full_name='CreditCardRequest.numberValidation', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='regex', full_name='CreditCardRequest.regex', index=4,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=182,
  serialized_end=293,
)


_CREDITCARDTABLEREQUEST = _descriptor.Descriptor(
  name='CreditCardTableRequest',
  full_name='CreditCardTableRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='page', full_name='CreditCardTableRequest.page', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='per_page', full_name='CreditCardTableRequest.per_page', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=15,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='search', full_name='CreditCardTableRequest.search', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=295,
  serialized_end=371,
)


_CREDITCARDSRESPONSE = _descriptor.Descriptor(
  name='CreditCardsResponse',
  full_name='CreditCardsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='credit', full_name='CreditCardsResponse.credit', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=373,
  serialized_end=430,
)


_CREDITCARDSMULTIPLERESPONSE = _descriptor.Descriptor(
  name='CreditCardsMultipleResponse',
  full_name='CreditCardsMultipleResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='credit', full_name='CreditCardsMultipleResponse.credit', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=432,
  serialized_end=497,
)


_CREDITCARDSTABLERESPONSE = _descriptor.Descriptor(
  name='CreditCardsTableResponse',
  full_name='CreditCardsTableResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='items', full_name='CreditCardsTableResponse.items', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='page', full_name='CreditCardsTableResponse.page', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='per_page', full_name='CreditCardsTableResponse.per_page', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='total_items', full_name='CreditCardsTableResponse.total_items', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='num_pages', full_name='CreditCardsTableResponse.num_pages', index=4,
      number=5, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=500,
  serialized_end=633,
)

_CREDITCARDSRESPONSE.fields_by_name['credit'].message_type = _CREDITCARDREQUEST
_CREDITCARDSMULTIPLERESPONSE.fields_by_name['credit'].message_type = _CREDITCARDREQUEST
_CREDITCARDSTABLERESPONSE.fields_by_name['items'].message_type = _CREDITCARDREQUEST
DESCRIPTOR.message_types_by_name['CreditCardEmpty'] = _CREDITCARDEMPTY
DESCRIPTOR.message_types_by_name['CreditCardIdRequest'] = _CREDITCARDIDREQUEST
DESCRIPTOR.message_types_by_name['CreditCardNotIdRequest'] = _CREDITCARDNOTIDREQUEST
DESCRIPTOR.message_types_by_name['CreditCardRequest'] = _CREDITCARDREQUEST
DESCRIPTOR.message_types_by_name['CreditCardTableRequest'] = _CREDITCARDTABLEREQUEST
DESCRIPTOR.message_types_by_name['CreditCardsResponse'] = _CREDITCARDSRESPONSE
DESCRIPTOR.message_types_by_name['CreditCardsMultipleResponse'] = _CREDITCARDSMULTIPLERESPONSE
DESCRIPTOR.message_types_by_name['CreditCardsTableResponse'] = _CREDITCARDSTABLERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CreditCardEmpty = _reflection.GeneratedProtocolMessageType('CreditCardEmpty', (_message.Message,), {
  'DESCRIPTOR' : _CREDITCARDEMPTY,
  '__module__' : 'credit_cards_pb2'
  # @@protoc_insertion_point(class_scope:CreditCardEmpty)
  })
_sym_db.RegisterMessage(CreditCardEmpty)

CreditCardIdRequest = _reflection.GeneratedProtocolMessageType('CreditCardIdRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREDITCARDIDREQUEST,
  '__module__' : 'credit_cards_pb2'
  # @@protoc_insertion_point(class_scope:CreditCardIdRequest)
  })
_sym_db.RegisterMessage(CreditCardIdRequest)

CreditCardNotIdRequest = _reflection.GeneratedProtocolMessageType('CreditCardNotIdRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREDITCARDNOTIDREQUEST,
  '__module__' : 'credit_cards_pb2'
  # @@protoc_insertion_point(class_scope:CreditCardNotIdRequest)
  })
_sym_db.RegisterMessage(CreditCardNotIdRequest)

CreditCardRequest = _reflection.GeneratedProtocolMessageType('CreditCardRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREDITCARDREQUEST,
  '__module__' : 'credit_cards_pb2'
  # @@protoc_insertion_point(class_scope:CreditCardRequest)
  })
_sym_db.RegisterMessage(CreditCardRequest)

CreditCardTableRequest = _reflection.GeneratedProtocolMessageType('CreditCardTableRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREDITCARDTABLEREQUEST,
  '__module__' : 'credit_cards_pb2'
  # @@protoc_insertion_point(class_scope:CreditCardTableRequest)
  })
_sym_db.RegisterMessage(CreditCardTableRequest)

CreditCardsResponse = _reflection.GeneratedProtocolMessageType('CreditCardsResponse', (_message.Message,), {
  'DESCRIPTOR' : _CREDITCARDSRESPONSE,
  '__module__' : 'credit_cards_pb2'
  # @@protoc_insertion_point(class_scope:CreditCardsResponse)
  })
_sym_db.RegisterMessage(CreditCardsResponse)

CreditCardsMultipleResponse = _reflection.GeneratedProtocolMessageType('CreditCardsMultipleResponse', (_message.Message,), {
  'DESCRIPTOR' : _CREDITCARDSMULTIPLERESPONSE,
  '__module__' : 'credit_cards_pb2'
  # @@protoc_insertion_point(class_scope:CreditCardsMultipleResponse)
  })
_sym_db.RegisterMessage(CreditCardsMultipleResponse)

CreditCardsTableResponse = _reflection.GeneratedProtocolMessageType('CreditCardsTableResponse', (_message.Message,), {
  'DESCRIPTOR' : _CREDITCARDSTABLERESPONSE,
  '__module__' : 'credit_cards_pb2'
  # @@protoc_insertion_point(class_scope:CreditCardsTableResponse)
  })
_sym_db.RegisterMessage(CreditCardsTableResponse)



_CREDITCARDS = _descriptor.ServiceDescriptor(
  name='CreditCards',
  full_name='CreditCards',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=636,
  serialized_end=981,
  methods=[
  _descriptor.MethodDescriptor(
    name='table',
    full_name='CreditCards.table',
    index=0,
    containing_service=None,
    input_type=_CREDITCARDTABLEREQUEST,
    output_type=_CREDITCARDSTABLERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='get_all',
    full_name='CreditCards.get_all',
    index=1,
    containing_service=None,
    input_type=_CREDITCARDEMPTY,
    output_type=_CREDITCARDSMULTIPLERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='get',
    full_name='CreditCards.get',
    index=2,
    containing_service=None,
    input_type=_CREDITCARDIDREQUEST,
    output_type=_CREDITCARDSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='save',
    full_name='CreditCards.save',
    index=3,
    containing_service=None,
    input_type=_CREDITCARDNOTIDREQUEST,
    output_type=_CREDITCARDSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='update',
    full_name='CreditCards.update',
    index=4,
    containing_service=None,
    input_type=_CREDITCARDREQUEST,
    output_type=_CREDITCARDSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='delete',
    full_name='CreditCards.delete',
    index=5,
    containing_service=None,
    input_type=_CREDITCARDIDREQUEST,
    output_type=_CREDITCARDSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CREDITCARDS)

DESCRIPTOR.services_by_name['CreditCards'] = _CREDITCARDS

# @@protoc_insertion_point(module_scope)
