# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import credit_cards_pb2 as credit__cards__pb2

class CreditCardsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.table = channel.unary_unary(
                '/CreditCards/table',
                request_serializer=credit__cards__pb2.CreditCardTableRequest.SerializeToString,
                response_deserializer=credit__cards__pb2.CreditCardsTableResponse.FromString,
                )
        self.get_all = channel.unary_unary(
                '/CreditCards/get_all',
                request_serializer=credit__cards__pb2.CreditCardEmpty.SerializeToString,
                response_deserializer=credit__cards__pb2.CreditCardsMultipleResponse.FromString,
                )
        self.get = channel.unary_unary(
                '/CreditCards/get',
                request_serializer=credit__cards__pb2.CreditCardIdRequest.SerializeToString,
                response_deserializer=credit__cards__pb2.CreditCardsResponse.FromString,
                )
        self.save = channel.unary_unary(
                '/CreditCards/save',
                request_serializer=credit__cards__pb2.CreditCardNotIdRequest.SerializeToString,
                response_deserializer=credit__cards__pb2.CreditCardsResponse.FromString,
                )
        self.update = channel.unary_unary(
                '/CreditCards/update',
                request_serializer=credit__cards__pb2.CreditCardRequest.SerializeToString,
                response_deserializer=credit__cards__pb2.CreditCardsResponse.FromString,
                )
        self.delete = channel.unary_unary(
                '/CreditCards/delete',
                request_serializer=credit__cards__pb2.CreditCardIdRequest.SerializeToString,
                response_deserializer=credit__cards__pb2.CreditCardsResponse.FromString,
                )


class CreditCardsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def table(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_all(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def save(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CreditCardsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'table': grpc.unary_unary_rpc_method_handler(
                    servicer.table,
                    request_deserializer=credit__cards__pb2.CreditCardTableRequest.FromString,
                    response_serializer=credit__cards__pb2.CreditCardsTableResponse.SerializeToString,
            ),
            'get_all': grpc.unary_unary_rpc_method_handler(
                    servicer.get_all,
                    request_deserializer=credit__cards__pb2.CreditCardEmpty.FromString,
                    response_serializer=credit__cards__pb2.CreditCardsMultipleResponse.SerializeToString,
            ),
            'get': grpc.unary_unary_rpc_method_handler(
                    servicer.get,
                    request_deserializer=credit__cards__pb2.CreditCardIdRequest.FromString,
                    response_serializer=credit__cards__pb2.CreditCardsResponse.SerializeToString,
            ),
            'save': grpc.unary_unary_rpc_method_handler(
                    servicer.save,
                    request_deserializer=credit__cards__pb2.CreditCardNotIdRequest.FromString,
                    response_serializer=credit__cards__pb2.CreditCardsResponse.SerializeToString,
            ),
            'update': grpc.unary_unary_rpc_method_handler(
                    servicer.update,
                    request_deserializer=credit__cards__pb2.CreditCardRequest.FromString,
                    response_serializer=credit__cards__pb2.CreditCardsResponse.SerializeToString,
            ),
            'delete': grpc.unary_unary_rpc_method_handler(
                    servicer.delete,
                    request_deserializer=credit__cards__pb2.CreditCardIdRequest.FromString,
                    response_serializer=credit__cards__pb2.CreditCardsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'CreditCards', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CreditCards(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def table(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/CreditCards/table',
            credit__cards__pb2.CreditCardTableRequest.SerializeToString,
            credit__cards__pb2.CreditCardsTableResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def get_all(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/CreditCards/get_all',
            credit__cards__pb2.CreditCardEmpty.SerializeToString,
            credit__cards__pb2.CreditCardsMultipleResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/CreditCards/get',
            credit__cards__pb2.CreditCardIdRequest.SerializeToString,
            credit__cards__pb2.CreditCardsResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def save(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/CreditCards/save',
            credit__cards__pb2.CreditCardNotIdRequest.SerializeToString,
            credit__cards__pb2.CreditCardsResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/CreditCards/update',
            credit__cards__pb2.CreditCardRequest.SerializeToString,
            credit__cards__pb2.CreditCardsResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/CreditCards/delete',
            credit__cards__pb2.CreditCardIdRequest.SerializeToString,
            credit__cards__pb2.CreditCardsResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
