# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: european_banks.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='european_banks.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14\x65uropean_banks.proto\"\x13\n\x11\x45uropeanBankEmpty\"#\n\x15\x45uropeanBankIdRequest\x12\n\n\x02id\x18\x01 \x02(\t\"Z\n\x18\x45uropeanBankNotIdRequest\x12\x10\n\x08\x62\x61nkName\x18\x01 \x02(\t\x12\r\n\x05swift\x18\x02 \x02(\t\x12\x0c\n\x04iban\x18\x03 \x02(\t\x12\x0f\n\x07\x63ountry\x18\x04 \x02(\t\"a\n\x13\x45uropeanBankRequest\x12\n\n\x02id\x18\x01 \x02(\t\x12\x10\n\x08\x62\x61nkName\x18\x02 \x02(\t\x12\r\n\x05swift\x18\x03 \x02(\t\x12\x0c\n\x04iban\x18\x04 \x02(\t\x12\x0f\n\x07\x63ountry\x18\x05 \x02(\t\"O\n\x19\x45uropeanBanksTableRequest\x12\x0c\n\x04page\x18\x01 \x02(\x05\x12\x14\n\x08per_page\x18\x02 \x01(\x05:\x02\x31\x35\x12\x0e\n\x06search\x18\x03 \x01(\t\"?\n\x15\x45uropeanBanksResponse\x12&\n\x08\x65uropean\x18\x01 \x02(\x0b\x32\x14.EuropeanBankRequest\"G\n\x1d\x45uropeanBanksMultipleResponse\x12&\n\x08\x65uropean\x18\x01 \x03(\x0b\x32\x14.EuropeanBankRequest\"\x89\x01\n\x1a\x45uropeanBanksTableResponse\x12#\n\x05items\x18\x01 \x03(\x0b\x32\x14.EuropeanBankRequest\x12\x0c\n\x04page\x18\x02 \x02(\x05\x12\x10\n\x08per_page\x18\x03 \x02(\x05\x12\x13\n\x0btotal_items\x18\x04 \x02(\x05\x12\x11\n\tnum_pages\x18\x05 \x02(\x05\x32\xf4\x02\n\rEuropeanBanks\x12@\n\x05table\x12\x1a.EuropeanBanksTableRequest\x1a\x1b.EuropeanBanksTableResponse\x12=\n\x07get_all\x12\x12.EuropeanBankEmpty\x1a\x1e.EuropeanBanksMultipleResponse\x12\x35\n\x03get\x12\x16.EuropeanBankIdRequest\x1a\x16.EuropeanBanksResponse\x12\x39\n\x04save\x12\x19.EuropeanBankNotIdRequest\x1a\x16.EuropeanBanksResponse\x12\x36\n\x06update\x12\x14.EuropeanBankRequest\x1a\x16.EuropeanBanksResponse\x12\x38\n\x06\x64\x65lete\x12\x16.EuropeanBankIdRequest\x1a\x16.EuropeanBanksResponse'
)




_EUROPEANBANKEMPTY = _descriptor.Descriptor(
  name='EuropeanBankEmpty',
  full_name='EuropeanBankEmpty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=43,
)


_EUROPEANBANKIDREQUEST = _descriptor.Descriptor(
  name='EuropeanBankIdRequest',
  full_name='EuropeanBankIdRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='EuropeanBankIdRequest.id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=80,
)


_EUROPEANBANKNOTIDREQUEST = _descriptor.Descriptor(
  name='EuropeanBankNotIdRequest',
  full_name='EuropeanBankNotIdRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='bankName', full_name='EuropeanBankNotIdRequest.bankName', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='swift', full_name='EuropeanBankNotIdRequest.swift', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='iban', full_name='EuropeanBankNotIdRequest.iban', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='country', full_name='EuropeanBankNotIdRequest.country', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=82,
  serialized_end=172,
)


_EUROPEANBANKREQUEST = _descriptor.Descriptor(
  name='EuropeanBankRequest',
  full_name='EuropeanBankRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='EuropeanBankRequest.id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bankName', full_name='EuropeanBankRequest.bankName', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='swift', full_name='EuropeanBankRequest.swift', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='iban', full_name='EuropeanBankRequest.iban', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='country', full_name='EuropeanBankRequest.country', index=4,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=174,
  serialized_end=271,
)


_EUROPEANBANKSTABLEREQUEST = _descriptor.Descriptor(
  name='EuropeanBanksTableRequest',
  full_name='EuropeanBanksTableRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='page', full_name='EuropeanBanksTableRequest.page', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='per_page', full_name='EuropeanBanksTableRequest.per_page', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=15,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='search', full_name='EuropeanBanksTableRequest.search', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=273,
  serialized_end=352,
)


_EUROPEANBANKSRESPONSE = _descriptor.Descriptor(
  name='EuropeanBanksResponse',
  full_name='EuropeanBanksResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='european', full_name='EuropeanBanksResponse.european', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=354,
  serialized_end=417,
)


_EUROPEANBANKSMULTIPLERESPONSE = _descriptor.Descriptor(
  name='EuropeanBanksMultipleResponse',
  full_name='EuropeanBanksMultipleResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='european', full_name='EuropeanBanksMultipleResponse.european', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=419,
  serialized_end=490,
)


_EUROPEANBANKSTABLERESPONSE = _descriptor.Descriptor(
  name='EuropeanBanksTableResponse',
  full_name='EuropeanBanksTableResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='items', full_name='EuropeanBanksTableResponse.items', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='page', full_name='EuropeanBanksTableResponse.page', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='per_page', full_name='EuropeanBanksTableResponse.per_page', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='total_items', full_name='EuropeanBanksTableResponse.total_items', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='num_pages', full_name='EuropeanBanksTableResponse.num_pages', index=4,
      number=5, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=493,
  serialized_end=630,
)

_EUROPEANBANKSRESPONSE.fields_by_name['european'].message_type = _EUROPEANBANKREQUEST
_EUROPEANBANKSMULTIPLERESPONSE.fields_by_name['european'].message_type = _EUROPEANBANKREQUEST
_EUROPEANBANKSTABLERESPONSE.fields_by_name['items'].message_type = _EUROPEANBANKREQUEST
DESCRIPTOR.message_types_by_name['EuropeanBankEmpty'] = _EUROPEANBANKEMPTY
DESCRIPTOR.message_types_by_name['EuropeanBankIdRequest'] = _EUROPEANBANKIDREQUEST
DESCRIPTOR.message_types_by_name['EuropeanBankNotIdRequest'] = _EUROPEANBANKNOTIDREQUEST
DESCRIPTOR.message_types_by_name['EuropeanBankRequest'] = _EUROPEANBANKREQUEST
DESCRIPTOR.message_types_by_name['EuropeanBanksTableRequest'] = _EUROPEANBANKSTABLEREQUEST
DESCRIPTOR.message_types_by_name['EuropeanBanksResponse'] = _EUROPEANBANKSRESPONSE
DESCRIPTOR.message_types_by_name['EuropeanBanksMultipleResponse'] = _EUROPEANBANKSMULTIPLERESPONSE
DESCRIPTOR.message_types_by_name['EuropeanBanksTableResponse'] = _EUROPEANBANKSTABLERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EuropeanBankEmpty = _reflection.GeneratedProtocolMessageType('EuropeanBankEmpty', (_message.Message,), {
  'DESCRIPTOR' : _EUROPEANBANKEMPTY,
  '__module__' : 'european_banks_pb2'
  # @@protoc_insertion_point(class_scope:EuropeanBankEmpty)
  })
_sym_db.RegisterMessage(EuropeanBankEmpty)

EuropeanBankIdRequest = _reflection.GeneratedProtocolMessageType('EuropeanBankIdRequest', (_message.Message,), {
  'DESCRIPTOR' : _EUROPEANBANKIDREQUEST,
  '__module__' : 'european_banks_pb2'
  # @@protoc_insertion_point(class_scope:EuropeanBankIdRequest)
  })
_sym_db.RegisterMessage(EuropeanBankIdRequest)

EuropeanBankNotIdRequest = _reflection.GeneratedProtocolMessageType('EuropeanBankNotIdRequest', (_message.Message,), {
  'DESCRIPTOR' : _EUROPEANBANKNOTIDREQUEST,
  '__module__' : 'european_banks_pb2'
  # @@protoc_insertion_point(class_scope:EuropeanBankNotIdRequest)
  })
_sym_db.RegisterMessage(EuropeanBankNotIdRequest)

EuropeanBankRequest = _reflection.GeneratedProtocolMessageType('EuropeanBankRequest', (_message.Message,), {
  'DESCRIPTOR' : _EUROPEANBANKREQUEST,
  '__module__' : 'european_banks_pb2'
  # @@protoc_insertion_point(class_scope:EuropeanBankRequest)
  })
_sym_db.RegisterMessage(EuropeanBankRequest)

EuropeanBanksTableRequest = _reflection.GeneratedProtocolMessageType('EuropeanBanksTableRequest', (_message.Message,), {
  'DESCRIPTOR' : _EUROPEANBANKSTABLEREQUEST,
  '__module__' : 'european_banks_pb2'
  # @@protoc_insertion_point(class_scope:EuropeanBanksTableRequest)
  })
_sym_db.RegisterMessage(EuropeanBanksTableRequest)

EuropeanBanksResponse = _reflection.GeneratedProtocolMessageType('EuropeanBanksResponse', (_message.Message,), {
  'DESCRIPTOR' : _EUROPEANBANKSRESPONSE,
  '__module__' : 'european_banks_pb2'
  # @@protoc_insertion_point(class_scope:EuropeanBanksResponse)
  })
_sym_db.RegisterMessage(EuropeanBanksResponse)

EuropeanBanksMultipleResponse = _reflection.GeneratedProtocolMessageType('EuropeanBanksMultipleResponse', (_message.Message,), {
  'DESCRIPTOR' : _EUROPEANBANKSMULTIPLERESPONSE,
  '__module__' : 'european_banks_pb2'
  # @@protoc_insertion_point(class_scope:EuropeanBanksMultipleResponse)
  })
_sym_db.RegisterMessage(EuropeanBanksMultipleResponse)

EuropeanBanksTableResponse = _reflection.GeneratedProtocolMessageType('EuropeanBanksTableResponse', (_message.Message,), {
  'DESCRIPTOR' : _EUROPEANBANKSTABLERESPONSE,
  '__module__' : 'european_banks_pb2'
  # @@protoc_insertion_point(class_scope:EuropeanBanksTableResponse)
  })
_sym_db.RegisterMessage(EuropeanBanksTableResponse)



_EUROPEANBANKS = _descriptor.ServiceDescriptor(
  name='EuropeanBanks',
  full_name='EuropeanBanks',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=633,
  serialized_end=1005,
  methods=[
  _descriptor.MethodDescriptor(
    name='table',
    full_name='EuropeanBanks.table',
    index=0,
    containing_service=None,
    input_type=_EUROPEANBANKSTABLEREQUEST,
    output_type=_EUROPEANBANKSTABLERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='get_all',
    full_name='EuropeanBanks.get_all',
    index=1,
    containing_service=None,
    input_type=_EUROPEANBANKEMPTY,
    output_type=_EUROPEANBANKSMULTIPLERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='get',
    full_name='EuropeanBanks.get',
    index=2,
    containing_service=None,
    input_type=_EUROPEANBANKIDREQUEST,
    output_type=_EUROPEANBANKSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='save',
    full_name='EuropeanBanks.save',
    index=3,
    containing_service=None,
    input_type=_EUROPEANBANKNOTIDREQUEST,
    output_type=_EUROPEANBANKSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='update',
    full_name='EuropeanBanks.update',
    index=4,
    containing_service=None,
    input_type=_EUROPEANBANKREQUEST,
    output_type=_EUROPEANBANKSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='delete',
    full_name='EuropeanBanks.delete',
    index=5,
    containing_service=None,
    input_type=_EUROPEANBANKIDREQUEST,
    output_type=_EUROPEANBANKSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_EUROPEANBANKS)

DESCRIPTOR.services_by_name['EuropeanBanks'] = _EUROPEANBANKS

# @@protoc_insertion_point(module_scope)
