# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import latinamerican_banks_pb2 as latinamerican__banks__pb2


class LatinAmericanBanksStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.table = channel.unary_unary(
                '/LatinAmericanBanks/table',
                request_serializer=latinamerican__banks__pb2.LatinAmericanBanksTableRequest.SerializeToString,
                response_deserializer=latinamerican__banks__pb2.LatinAmericanBanksTableResponse.FromString,
                )
        self.get_all = channel.unary_unary(
                '/LatinAmericanBanks/get_all',
                request_serializer=latinamerican__banks__pb2.LatinAmericanBankEmpty.SerializeToString,
                response_deserializer=latinamerican__banks__pb2.LatinAmericanBanksMultipleResponse.FromString,
                )
        self.get = channel.unary_unary(
                '/LatinAmericanBanks/get',
                request_serializer=latinamerican__banks__pb2.LatinAmericanBankIdRequest.SerializeToString,
                response_deserializer=latinamerican__banks__pb2.LatinAmericanBanksResponse.FromString,
                )
        self.save = channel.unary_unary(
                '/LatinAmericanBanks/save',
                request_serializer=latinamerican__banks__pb2.LatinAmericanBankNotIdRequest.SerializeToString,
                response_deserializer=latinamerican__banks__pb2.LatinAmericanBanksResponse.FromString,
                )
        self.update = channel.unary_unary(
                '/LatinAmericanBanks/update',
                request_serializer=latinamerican__banks__pb2.LatinAmericanBankRequest.SerializeToString,
                response_deserializer=latinamerican__banks__pb2.LatinAmericanBanksResponse.FromString,
                )
        self.delete = channel.unary_unary(
                '/LatinAmericanBanks/delete',
                request_serializer=latinamerican__banks__pb2.LatinAmericanBankIdRequest.SerializeToString,
                response_deserializer=latinamerican__banks__pb2.LatinAmericanBanksResponse.FromString,
                )


class LatinAmericanBanksServicer(object):
    """Missing associated documentation comment in .proto file."""

    def table(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_all(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def save(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LatinAmericanBanksServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'table': grpc.unary_unary_rpc_method_handler(
                    servicer.table,
                    request_deserializer=latinamerican__banks__pb2.LatinAmericanBanksTableRequest.FromString,
                    response_serializer=latinamerican__banks__pb2.LatinAmericanBanksTableResponse.SerializeToString,
            ),
            'get_all': grpc.unary_unary_rpc_method_handler(
                    servicer.get_all,
                    request_deserializer=latinamerican__banks__pb2.LatinAmericanBankEmpty.FromString,
                    response_serializer=latinamerican__banks__pb2.LatinAmericanBanksMultipleResponse.SerializeToString,
            ),
            'get': grpc.unary_unary_rpc_method_handler(
                    servicer.get,
                    request_deserializer=latinamerican__banks__pb2.LatinAmericanBankIdRequest.FromString,
                    response_serializer=latinamerican__banks__pb2.LatinAmericanBanksResponse.SerializeToString,
            ),
            'save': grpc.unary_unary_rpc_method_handler(
                    servicer.save,
                    request_deserializer=latinamerican__banks__pb2.LatinAmericanBankNotIdRequest.FromString,
                    response_serializer=latinamerican__banks__pb2.LatinAmericanBanksResponse.SerializeToString,
            ),
            'update': grpc.unary_unary_rpc_method_handler(
                    servicer.update,
                    request_deserializer=latinamerican__banks__pb2.LatinAmericanBankRequest.FromString,
                    response_serializer=latinamerican__banks__pb2.LatinAmericanBanksResponse.SerializeToString,
            ),
            'delete': grpc.unary_unary_rpc_method_handler(
                    servicer.delete,
                    request_deserializer=latinamerican__banks__pb2.LatinAmericanBankIdRequest.FromString,
                    response_serializer=latinamerican__banks__pb2.LatinAmericanBanksResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'LatinAmericanBanks', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class LatinAmericanBanks(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def table(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/LatinAmericanBanks/table',
            latinamerican__banks__pb2.LatinAmericanBanksTableRequest.SerializeToString,
            latinamerican__banks__pb2.LatinAmericanBanksTableResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def get_all(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/LatinAmericanBanks/get_all',
            latinamerican__banks__pb2.LatinAmericanBankEmpty.SerializeToString,
            latinamerican__banks__pb2.LatinAmericanBanksMultipleResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/LatinAmericanBanks/get',
            latinamerican__banks__pb2.LatinAmericanBankIdRequest.SerializeToString,
            latinamerican__banks__pb2.LatinAmericanBanksResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def save(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/LatinAmericanBanks/save',
            latinamerican__banks__pb2.LatinAmericanBankNotIdRequest.SerializeToString,
            latinamerican__banks__pb2.LatinAmericanBanksResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/LatinAmericanBanks/update',
            latinamerican__banks__pb2.LatinAmericanBankRequest.SerializeToString,
            latinamerican__banks__pb2.LatinAmericanBanksResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/LatinAmericanBanks/delete',
            latinamerican__banks__pb2.LatinAmericanBankIdRequest.SerializeToString,
            latinamerican__banks__pb2.LatinAmericanBanksResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
