# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: latinamerican_banks.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='latinamerican_banks.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x19latinamerican_banks.proto\"\x18\n\x16LatinAmericanBankEmpty\"(\n\x1aLatinAmericanBankIdRequest\x12\n\n\x02id\x18\x01 \x02(\t\"Q\n\x1dLatinAmericanBankNotIdRequest\x12\x10\n\x08\x62\x61nkName\x18\x01 \x02(\t\x12\r\n\x05swift\x18\x02 \x02(\t\x12\x0f\n\x07\x63ountry\x18\x03 \x02(\t\"X\n\x18LatinAmericanBankRequest\x12\n\n\x02id\x18\x01 \x02(\t\x12\x10\n\x08\x62\x61nkName\x18\x02 \x02(\t\x12\r\n\x05swift\x18\x03 \x02(\t\x12\x0f\n\x07\x63ountry\x18\x04 \x02(\t\"T\n\x1eLatinAmericanBanksTableRequest\x12\x0c\n\x04page\x18\x01 \x02(\x05\x12\x14\n\x08per_page\x18\x02 \x01(\x05:\x02\x31\x35\x12\x0e\n\x06search\x18\x03 \x01(\t\"F\n\x1aLatinAmericanBanksResponse\x12(\n\x05latin\x18\x01 \x02(\x0b\x32\x19.LatinAmericanBankRequest\"N\n\"LatinAmericanBanksMultipleResponse\x12(\n\x05latin\x18\x01 \x03(\x0b\x32\x19.LatinAmericanBankRequest\"\x93\x01\n\x1fLatinAmericanBanksTableResponse\x12(\n\x05items\x18\x01 \x03(\x0b\x32\x19.LatinAmericanBankRequest\x12\x0c\n\x04page\x18\x02 \x02(\x05\x12\x10\n\x08per_page\x18\x03 \x02(\x05\x12\x13\n\x0btotal_items\x18\x04 \x02(\x05\x12\x11\n\tnum_pages\x18\x05 \x02(\x05\x32\xb5\x03\n\x12LatinAmericanBanks\x12J\n\x05table\x12\x1f.LatinAmericanBanksTableRequest\x1a .LatinAmericanBanksTableResponse\x12G\n\x07get_all\x12\x17.LatinAmericanBankEmpty\x1a#.LatinAmericanBanksMultipleResponse\x12?\n\x03get\x12\x1b.LatinAmericanBankIdRequest\x1a\x1b.LatinAmericanBanksResponse\x12\x43\n\x04save\x12\x1e.LatinAmericanBankNotIdRequest\x1a\x1b.LatinAmericanBanksResponse\x12@\n\x06update\x12\x19.LatinAmericanBankRequest\x1a\x1b.LatinAmericanBanksResponse\x12\x42\n\x06\x64\x65lete\x12\x1b.LatinAmericanBankIdRequest\x1a\x1b.LatinAmericanBanksResponse'
)




_LATINAMERICANBANKEMPTY = _descriptor.Descriptor(
  name='LatinAmericanBankEmpty',
  full_name='LatinAmericanBankEmpty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=53,
)


_LATINAMERICANBANKIDREQUEST = _descriptor.Descriptor(
  name='LatinAmericanBankIdRequest',
  full_name='LatinAmericanBankIdRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='LatinAmericanBankIdRequest.id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=95,
)


_LATINAMERICANBANKNOTIDREQUEST = _descriptor.Descriptor(
  name='LatinAmericanBankNotIdRequest',
  full_name='LatinAmericanBankNotIdRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='bankName', full_name='LatinAmericanBankNotIdRequest.bankName', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='swift', full_name='LatinAmericanBankNotIdRequest.swift', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='country', full_name='LatinAmericanBankNotIdRequest.country', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=97,
  serialized_end=178,
)


_LATINAMERICANBANKREQUEST = _descriptor.Descriptor(
  name='LatinAmericanBankRequest',
  full_name='LatinAmericanBankRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='LatinAmericanBankRequest.id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bankName', full_name='LatinAmericanBankRequest.bankName', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='swift', full_name='LatinAmericanBankRequest.swift', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='country', full_name='LatinAmericanBankRequest.country', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=180,
  serialized_end=268,
)


_LATINAMERICANBANKSTABLEREQUEST = _descriptor.Descriptor(
  name='LatinAmericanBanksTableRequest',
  full_name='LatinAmericanBanksTableRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='page', full_name='LatinAmericanBanksTableRequest.page', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='per_page', full_name='LatinAmericanBanksTableRequest.per_page', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=15,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='search', full_name='LatinAmericanBanksTableRequest.search', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=270,
  serialized_end=354,
)


_LATINAMERICANBANKSRESPONSE = _descriptor.Descriptor(
  name='LatinAmericanBanksResponse',
  full_name='LatinAmericanBanksResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='latin', full_name='LatinAmericanBanksResponse.latin', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=356,
  serialized_end=426,
)


_LATINAMERICANBANKSMULTIPLERESPONSE = _descriptor.Descriptor(
  name='LatinAmericanBanksMultipleResponse',
  full_name='LatinAmericanBanksMultipleResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='latin', full_name='LatinAmericanBanksMultipleResponse.latin', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=428,
  serialized_end=506,
)


_LATINAMERICANBANKSTABLERESPONSE = _descriptor.Descriptor(
  name='LatinAmericanBanksTableResponse',
  full_name='LatinAmericanBanksTableResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='items', full_name='LatinAmericanBanksTableResponse.items', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='page', full_name='LatinAmericanBanksTableResponse.page', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='per_page', full_name='LatinAmericanBanksTableResponse.per_page', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='total_items', full_name='LatinAmericanBanksTableResponse.total_items', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='num_pages', full_name='LatinAmericanBanksTableResponse.num_pages', index=4,
      number=5, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=509,
  serialized_end=656,
)

_LATINAMERICANBANKSRESPONSE.fields_by_name['latin'].message_type = _LATINAMERICANBANKREQUEST
_LATINAMERICANBANKSMULTIPLERESPONSE.fields_by_name['latin'].message_type = _LATINAMERICANBANKREQUEST
_LATINAMERICANBANKSTABLERESPONSE.fields_by_name['items'].message_type = _LATINAMERICANBANKREQUEST
DESCRIPTOR.message_types_by_name['LatinAmericanBankEmpty'] = _LATINAMERICANBANKEMPTY
DESCRIPTOR.message_types_by_name['LatinAmericanBankIdRequest'] = _LATINAMERICANBANKIDREQUEST
DESCRIPTOR.message_types_by_name['LatinAmericanBankNotIdRequest'] = _LATINAMERICANBANKNOTIDREQUEST
DESCRIPTOR.message_types_by_name['LatinAmericanBankRequest'] = _LATINAMERICANBANKREQUEST
DESCRIPTOR.message_types_by_name['LatinAmericanBanksTableRequest'] = _LATINAMERICANBANKSTABLEREQUEST
DESCRIPTOR.message_types_by_name['LatinAmericanBanksResponse'] = _LATINAMERICANBANKSRESPONSE
DESCRIPTOR.message_types_by_name['LatinAmericanBanksMultipleResponse'] = _LATINAMERICANBANKSMULTIPLERESPONSE
DESCRIPTOR.message_types_by_name['LatinAmericanBanksTableResponse'] = _LATINAMERICANBANKSTABLERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LatinAmericanBankEmpty = _reflection.GeneratedProtocolMessageType('LatinAmericanBankEmpty', (_message.Message,), {
  'DESCRIPTOR' : _LATINAMERICANBANKEMPTY,
  '__module__' : 'latinamerican_banks_pb2'
  # @@protoc_insertion_point(class_scope:LatinAmericanBankEmpty)
  })
_sym_db.RegisterMessage(LatinAmericanBankEmpty)

LatinAmericanBankIdRequest = _reflection.GeneratedProtocolMessageType('LatinAmericanBankIdRequest', (_message.Message,), {
  'DESCRIPTOR' : _LATINAMERICANBANKIDREQUEST,
  '__module__' : 'latinamerican_banks_pb2'
  # @@protoc_insertion_point(class_scope:LatinAmericanBankIdRequest)
  })
_sym_db.RegisterMessage(LatinAmericanBankIdRequest)

LatinAmericanBankNotIdRequest = _reflection.GeneratedProtocolMessageType('LatinAmericanBankNotIdRequest', (_message.Message,), {
  'DESCRIPTOR' : _LATINAMERICANBANKNOTIDREQUEST,
  '__module__' : 'latinamerican_banks_pb2'
  # @@protoc_insertion_point(class_scope:LatinAmericanBankNotIdRequest)
  })
_sym_db.RegisterMessage(LatinAmericanBankNotIdRequest)

LatinAmericanBankRequest = _reflection.GeneratedProtocolMessageType('LatinAmericanBankRequest', (_message.Message,), {
  'DESCRIPTOR' : _LATINAMERICANBANKREQUEST,
  '__module__' : 'latinamerican_banks_pb2'
  # @@protoc_insertion_point(class_scope:LatinAmericanBankRequest)
  })
_sym_db.RegisterMessage(LatinAmericanBankRequest)

LatinAmericanBanksTableRequest = _reflection.GeneratedProtocolMessageType('LatinAmericanBanksTableRequest', (_message.Message,), {
  'DESCRIPTOR' : _LATINAMERICANBANKSTABLEREQUEST,
  '__module__' : 'latinamerican_banks_pb2'
  # @@protoc_insertion_point(class_scope:LatinAmericanBanksTableRequest)
  })
_sym_db.RegisterMessage(LatinAmericanBanksTableRequest)

LatinAmericanBanksResponse = _reflection.GeneratedProtocolMessageType('LatinAmericanBanksResponse', (_message.Message,), {
  'DESCRIPTOR' : _LATINAMERICANBANKSRESPONSE,
  '__module__' : 'latinamerican_banks_pb2'
  # @@protoc_insertion_point(class_scope:LatinAmericanBanksResponse)
  })
_sym_db.RegisterMessage(LatinAmericanBanksResponse)

LatinAmericanBanksMultipleResponse = _reflection.GeneratedProtocolMessageType('LatinAmericanBanksMultipleResponse', (_message.Message,), {
  'DESCRIPTOR' : _LATINAMERICANBANKSMULTIPLERESPONSE,
  '__module__' : 'latinamerican_banks_pb2'
  # @@protoc_insertion_point(class_scope:LatinAmericanBanksMultipleResponse)
  })
_sym_db.RegisterMessage(LatinAmericanBanksMultipleResponse)

LatinAmericanBanksTableResponse = _reflection.GeneratedProtocolMessageType('LatinAmericanBanksTableResponse', (_message.Message,), {
  'DESCRIPTOR' : _LATINAMERICANBANKSTABLERESPONSE,
  '__module__' : 'latinamerican_banks_pb2'
  # @@protoc_insertion_point(class_scope:LatinAmericanBanksTableResponse)
  })
_sym_db.RegisterMessage(LatinAmericanBanksTableResponse)



_LATINAMERICANBANKS = _descriptor.ServiceDescriptor(
  name='LatinAmericanBanks',
  full_name='LatinAmericanBanks',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=659,
  serialized_end=1096,
  methods=[
  _descriptor.MethodDescriptor(
    name='table',
    full_name='LatinAmericanBanks.table',
    index=0,
    containing_service=None,
    input_type=_LATINAMERICANBANKSTABLEREQUEST,
    output_type=_LATINAMERICANBANKSTABLERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='get_all',
    full_name='LatinAmericanBanks.get_all',
    index=1,
    containing_service=None,
    input_type=_LATINAMERICANBANKEMPTY,
    output_type=_LATINAMERICANBANKSMULTIPLERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='get',
    full_name='LatinAmericanBanks.get',
    index=2,
    containing_service=None,
    input_type=_LATINAMERICANBANKIDREQUEST,
    output_type=_LATINAMERICANBANKSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='save',
    full_name='LatinAmericanBanks.save',
    index=3,
    containing_service=None,
    input_type=_LATINAMERICANBANKNOTIDREQUEST,
    output_type=_LATINAMERICANBANKSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='update',
    full_name='LatinAmericanBanks.update',
    index=4,
    containing_service=None,
    input_type=_LATINAMERICANBANKREQUEST,
    output_type=_LATINAMERICANBANKSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='delete',
    full_name='LatinAmericanBanks.delete',
    index=5,
    containing_service=None,
    input_type=_LATINAMERICANBANKIDREQUEST,
    output_type=_LATINAMERICANBANKSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_LATINAMERICANBANKS)

DESCRIPTOR.services_by_name['LatinAmericanBanks'] = _LATINAMERICANBANKS

# @@protoc_insertion_point(module_scope)
