# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: city.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='city.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\ncity.proto\"\x0b\n\tCityEmpty\"\x1b\n\rCityIdRequest\x12\n\n\x02id\x18\x01 \x02(\t\"/\n\x10\x43ityNotIdRequest\x12\r\n\x05state\x18\x01 \x02(\t\x12\x0c\n\x04name\x18\x02 \x02(\t\"6\n\x0b\x43ityRequest\x12\n\n\x02id\x18\x01 \x02(\t\x12\r\n\x05state\x18\x02 \x02(\t\x12\x0c\n\x04name\x18\x03 \x02(\t\"F\n\x10\x43ityTableRequest\x12\x0c\n\x04page\x18\x01 \x02(\x05\x12\x14\n\x08per_page\x18\x02 \x01(\x05:\x02\x31\x35\x12\x0e\n\x06search\x18\x03 \x01(\t\"*\n\x0c\x43ityResponse\x12\x1a\n\x04\x63ity\x18\x01 \x02(\x0b\x32\x0c.CityRequest\"2\n\x14\x43ityMultipleResponse\x12\x1a\n\x04\x63ity\x18\x01 \x03(\x0b\x32\x0c.CityRequest\"x\n\x11\x43ityTableResponse\x12\x1b\n\x05items\x18\x01 \x03(\x0b\x32\x0c.CityRequest\x12\x0c\n\x04page\x18\x02 \x02(\x05\x12\x10\n\x08per_page\x18\x03 \x02(\x05\x12\x13\n\x0btotal_items\x18\x04 \x02(\x05\x12\x11\n\tnum_pages\x18\x05 \x02(\x05\x32\x81\x02\n\x04\x43ity\x12.\n\x05table\x12\x11.CityTableRequest\x1a\x12.CityTableResponse\x12,\n\x07get_all\x12\n.CityEmpty\x1a\x15.CityMultipleResponse\x12$\n\x03get\x12\x0e.CityIdRequest\x1a\r.CityResponse\x12(\n\x04save\x12\x11.CityNotIdRequest\x1a\r.CityResponse\x12%\n\x06update\x12\x0c.CityRequest\x1a\r.CityResponse\x12$\n\x06\x64\x65lete\x12\x0e.CityIdRequest\x1a\n.CityEmpty'
)




_CITYEMPTY = _descriptor.Descriptor(
  name='CityEmpty',
  full_name='CityEmpty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=25,
)


_CITYIDREQUEST = _descriptor.Descriptor(
  name='CityIdRequest',
  full_name='CityIdRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='CityIdRequest.id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=54,
)


_CITYNOTIDREQUEST = _descriptor.Descriptor(
  name='CityNotIdRequest',
  full_name='CityNotIdRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='state', full_name='CityNotIdRequest.state', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='CityNotIdRequest.name', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=103,
)


_CITYREQUEST = _descriptor.Descriptor(
  name='CityRequest',
  full_name='CityRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='CityRequest.id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='state', full_name='CityRequest.state', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='CityRequest.name', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=105,
  serialized_end=159,
)


_CITYTABLEREQUEST = _descriptor.Descriptor(
  name='CityTableRequest',
  full_name='CityTableRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='page', full_name='CityTableRequest.page', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='per_page', full_name='CityTableRequest.per_page', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=15,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='search', full_name='CityTableRequest.search', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=161,
  serialized_end=231,
)


_CITYRESPONSE = _descriptor.Descriptor(
  name='CityResponse',
  full_name='CityResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='city', full_name='CityResponse.city', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=233,
  serialized_end=275,
)


_CITYMULTIPLERESPONSE = _descriptor.Descriptor(
  name='CityMultipleResponse',
  full_name='CityMultipleResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='city', full_name='CityMultipleResponse.city', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=277,
  serialized_end=327,
)


_CITYTABLERESPONSE = _descriptor.Descriptor(
  name='CityTableResponse',
  full_name='CityTableResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='items', full_name='CityTableResponse.items', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='page', full_name='CityTableResponse.page', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='per_page', full_name='CityTableResponse.per_page', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='total_items', full_name='CityTableResponse.total_items', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='num_pages', full_name='CityTableResponse.num_pages', index=4,
      number=5, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=329,
  serialized_end=449,
)

_CITYRESPONSE.fields_by_name['city'].message_type = _CITYREQUEST
_CITYMULTIPLERESPONSE.fields_by_name['city'].message_type = _CITYREQUEST
_CITYTABLERESPONSE.fields_by_name['items'].message_type = _CITYREQUEST
DESCRIPTOR.message_types_by_name['CityEmpty'] = _CITYEMPTY
DESCRIPTOR.message_types_by_name['CityIdRequest'] = _CITYIDREQUEST
DESCRIPTOR.message_types_by_name['CityNotIdRequest'] = _CITYNOTIDREQUEST
DESCRIPTOR.message_types_by_name['CityRequest'] = _CITYREQUEST
DESCRIPTOR.message_types_by_name['CityTableRequest'] = _CITYTABLEREQUEST
DESCRIPTOR.message_types_by_name['CityResponse'] = _CITYRESPONSE
DESCRIPTOR.message_types_by_name['CityMultipleResponse'] = _CITYMULTIPLERESPONSE
DESCRIPTOR.message_types_by_name['CityTableResponse'] = _CITYTABLERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CityEmpty = _reflection.GeneratedProtocolMessageType('CityEmpty', (_message.Message,), {
  'DESCRIPTOR' : _CITYEMPTY,
  '__module__' : 'city_pb2'
  # @@protoc_insertion_point(class_scope:CityEmpty)
  })
_sym_db.RegisterMessage(CityEmpty)

CityIdRequest = _reflection.GeneratedProtocolMessageType('CityIdRequest', (_message.Message,), {
  'DESCRIPTOR' : _CITYIDREQUEST,
  '__module__' : 'city_pb2'
  # @@protoc_insertion_point(class_scope:CityIdRequest)
  })
_sym_db.RegisterMessage(CityIdRequest)

CityNotIdRequest = _reflection.GeneratedProtocolMessageType('CityNotIdRequest', (_message.Message,), {
  'DESCRIPTOR' : _CITYNOTIDREQUEST,
  '__module__' : 'city_pb2'
  # @@protoc_insertion_point(class_scope:CityNotIdRequest)
  })
_sym_db.RegisterMessage(CityNotIdRequest)

CityRequest = _reflection.GeneratedProtocolMessageType('CityRequest', (_message.Message,), {
  'DESCRIPTOR' : _CITYREQUEST,
  '__module__' : 'city_pb2'
  # @@protoc_insertion_point(class_scope:CityRequest)
  })
_sym_db.RegisterMessage(CityRequest)

CityTableRequest = _reflection.GeneratedProtocolMessageType('CityTableRequest', (_message.Message,), {
  'DESCRIPTOR' : _CITYTABLEREQUEST,
  '__module__' : 'city_pb2'
  # @@protoc_insertion_point(class_scope:CityTableRequest)
  })
_sym_db.RegisterMessage(CityTableRequest)

CityResponse = _reflection.GeneratedProtocolMessageType('CityResponse', (_message.Message,), {
  'DESCRIPTOR' : _CITYRESPONSE,
  '__module__' : 'city_pb2'
  # @@protoc_insertion_point(class_scope:CityResponse)
  })
_sym_db.RegisterMessage(CityResponse)

CityMultipleResponse = _reflection.GeneratedProtocolMessageType('CityMultipleResponse', (_message.Message,), {
  'DESCRIPTOR' : _CITYMULTIPLERESPONSE,
  '__module__' : 'city_pb2'
  # @@protoc_insertion_point(class_scope:CityMultipleResponse)
  })
_sym_db.RegisterMessage(CityMultipleResponse)

CityTableResponse = _reflection.GeneratedProtocolMessageType('CityTableResponse', (_message.Message,), {
  'DESCRIPTOR' : _CITYTABLERESPONSE,
  '__module__' : 'city_pb2'
  # @@protoc_insertion_point(class_scope:CityTableResponse)
  })
_sym_db.RegisterMessage(CityTableResponse)



_CITY = _descriptor.ServiceDescriptor(
  name='City',
  full_name='City',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=452,
  serialized_end=709,
  methods=[
  _descriptor.MethodDescriptor(
    name='table',
    full_name='City.table',
    index=0,
    containing_service=None,
    input_type=_CITYTABLEREQUEST,
    output_type=_CITYTABLERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='get_all',
    full_name='City.get_all',
    index=1,
    containing_service=None,
    input_type=_CITYEMPTY,
    output_type=_CITYMULTIPLERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='get',
    full_name='City.get',
    index=2,
    containing_service=None,
    input_type=_CITYIDREQUEST,
    output_type=_CITYRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='save',
    full_name='City.save',
    index=3,
    containing_service=None,
    input_type=_CITYNOTIDREQUEST,
    output_type=_CITYRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='update',
    full_name='City.update',
    index=4,
    containing_service=None,
    input_type=_CITYREQUEST,
    output_type=_CITYRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='delete',
    full_name='City.delete',
    index=5,
    containing_service=None,
    input_type=_CITYIDREQUEST,
    output_type=_CITYEMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CITY)

DESCRIPTOR.services_by_name['City'] = _CITY

# @@protoc_insertion_point(module_scope)
