# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import country_pb2 as country__pb2


class CountryStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.table = channel.unary_unary(
                '/country.Country/table',
                request_serializer=country__pb2.CountryTableRequest.SerializeToString,
                response_deserializer=country__pb2.CountryTableResponse.FromString,
                )
        self.get_all = channel.unary_unary(
                '/country.Country/get_all',
                request_serializer=country__pb2.CountryEmpty.SerializeToString,
                response_deserializer=country__pb2.CountryMultipleResponse.FromString,
                )
        self.get = channel.unary_unary(
                '/country.Country/get',
                request_serializer=country__pb2.CountryIdRequest.SerializeToString,
                response_deserializer=country__pb2.CountryResponse.FromString,
                )
        self.save = channel.unary_unary(
                '/country.Country/save',
                request_serializer=country__pb2.CountryNotIdRequest.SerializeToString,
                response_deserializer=country__pb2.CountryResponse.FromString,
                )
        self.update = channel.unary_unary(
                '/country.Country/update',
                request_serializer=country__pb2.CountryRequest.SerializeToString,
                response_deserializer=country__pb2.CountryResponse.FromString,
                )
        self.delete = channel.unary_unary(
                '/country.Country/delete',
                request_serializer=country__pb2.CountryIdRequest.SerializeToString,
                response_deserializer=country__pb2.CountryEmpty.FromString,
                )


class CountryServicer(object):
    """Missing associated documentation comment in .proto file."""

    def table(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_all(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def save(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CountryServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'table': grpc.unary_unary_rpc_method_handler(
                    servicer.table,
                    request_deserializer=country__pb2.CountryTableRequest.FromString,
                    response_serializer=country__pb2.CountryTableResponse.SerializeToString,
            ),
            'get_all': grpc.unary_unary_rpc_method_handler(
                    servicer.get_all,
                    request_deserializer=country__pb2.CountryEmpty.FromString,
                    response_serializer=country__pb2.CountryMultipleResponse.SerializeToString,
            ),
            'get': grpc.unary_unary_rpc_method_handler(
                    servicer.get,
                    request_deserializer=country__pb2.CountryIdRequest.FromString,
                    response_serializer=country__pb2.CountryResponse.SerializeToString,
            ),
            'save': grpc.unary_unary_rpc_method_handler(
                    servicer.save,
                    request_deserializer=country__pb2.CountryNotIdRequest.FromString,
                    response_serializer=country__pb2.CountryResponse.SerializeToString,
            ),
            'update': grpc.unary_unary_rpc_method_handler(
                    servicer.update,
                    request_deserializer=country__pb2.CountryRequest.FromString,
                    response_serializer=country__pb2.CountryResponse.SerializeToString,
            ),
            'delete': grpc.unary_unary_rpc_method_handler(
                    servicer.delete,
                    request_deserializer=country__pb2.CountryIdRequest.FromString,
                    response_serializer=country__pb2.CountryEmpty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'country.Country', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Country(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def table(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/country.Country/table',
            country__pb2.CountryTableRequest.SerializeToString,
            country__pb2.CountryTableResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def get_all(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/country.Country/get_all',
            country__pb2.CountryEmpty.SerializeToString,
            country__pb2.CountryMultipleResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/country.Country/get',
            country__pb2.CountryIdRequest.SerializeToString,
            country__pb2.CountryResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def save(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/country.Country/save',
            country__pb2.CountryNotIdRequest.SerializeToString,
            country__pb2.CountryResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/country.Country/update',
            country__pb2.CountryRequest.SerializeToString,
            country__pb2.CountryResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/country.Country/delete',
            country__pb2.CountryIdRequest.SerializeToString,
            country__pb2.CountryEmpty.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
