# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: state.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='state.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0bstate.proto\"\x0c\n\nStateEmpty\"\x1c\n\x0eStateIdRequest\x12\n\n\x02id\x18\x01 \x02(\t\"1\n\x06\x43ities\x12\n\n\x02id\x18\x01 \x02(\t\x12\r\n\x05state\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\"K\n\x11StateNotIdRequest\x12\x0f\n\x07\x63ountry\x18\x01 \x02(\t\x12\x0c\n\x04name\x18\x02 \x02(\t\x12\x17\n\x06\x63ities\x18\x03 \x03(\x0b\x32\x07.Cities\"R\n\x0cStateRequest\x12\n\n\x02id\x18\x01 \x02(\t\x12\x0f\n\x07\x63ountry\x18\x02 \x02(\t\x12\x0c\n\x04name\x18\x03 \x02(\t\x12\x17\n\x06\x63ities\x18\x04 \x03(\x0b\x32\x07.Cities\"G\n\x11StateTableRequest\x12\x0c\n\x04page\x18\x01 \x02(\x05\x12\x14\n\x08per_page\x18\x02 \x01(\x05:\x02\x31\x35\x12\x0e\n\x06search\x18\x03 \x01(\t\"-\n\rStateResponse\x12\x1c\n\x05state\x18\x01 \x02(\x0b\x32\r.StateRequest\"5\n\x15StateMultipleResponse\x12\x1c\n\x05state\x18\x01 \x03(\x0b\x32\r.StateRequest\"z\n\x12StateTableResponse\x12\x1c\n\x05items\x18\x01 \x03(\x0b\x32\r.StateRequest\x12\x0c\n\x04page\x18\x02 \x02(\x05\x12\x10\n\x08per_page\x18\x03 \x02(\x05\x12\x13\n\x0btotal_items\x18\x04 \x02(\x05\x12\x11\n\tnum_pages\x18\x05 \x02(\x05\x32\x8e\x02\n\x05State\x12\x30\n\x05table\x12\x12.StateTableRequest\x1a\x13.StateTableResponse\x12.\n\x07get_all\x12\x0b.StateEmpty\x1a\x16.StateMultipleResponse\x12&\n\x03get\x12\x0f.StateIdRequest\x1a\x0e.StateResponse\x12*\n\x04save\x12\x12.StateNotIdRequest\x1a\x0e.StateResponse\x12\'\n\x06update\x12\r.StateRequest\x1a\x0e.StateResponse\x12&\n\x06\x64\x65lete\x12\x0f.StateIdRequest\x1a\x0b.StateEmpty'
)




_STATEEMPTY = _descriptor.Descriptor(
  name='StateEmpty',
  full_name='StateEmpty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=27,
)


_STATEIDREQUEST = _descriptor.Descriptor(
  name='StateIdRequest',
  full_name='StateIdRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='StateIdRequest.id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=57,
)


_CITIES = _descriptor.Descriptor(
  name='Cities',
  full_name='Cities',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Cities.id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='state', full_name='Cities.state', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='Cities.name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=59,
  serialized_end=108,
)


_STATENOTIDREQUEST = _descriptor.Descriptor(
  name='StateNotIdRequest',
  full_name='StateNotIdRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='country', full_name='StateNotIdRequest.country', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='StateNotIdRequest.name', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cities', full_name='StateNotIdRequest.cities', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=110,
  serialized_end=185,
)


_STATEREQUEST = _descriptor.Descriptor(
  name='StateRequest',
  full_name='StateRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='StateRequest.id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='country', full_name='StateRequest.country', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='StateRequest.name', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cities', full_name='StateRequest.cities', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=187,
  serialized_end=269,
)


_STATETABLEREQUEST = _descriptor.Descriptor(
  name='StateTableRequest',
  full_name='StateTableRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='page', full_name='StateTableRequest.page', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='per_page', full_name='StateTableRequest.per_page', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=15,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='search', full_name='StateTableRequest.search', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=271,
  serialized_end=342,
)


_STATERESPONSE = _descriptor.Descriptor(
  name='StateResponse',
  full_name='StateResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='state', full_name='StateResponse.state', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=344,
  serialized_end=389,
)


_STATEMULTIPLERESPONSE = _descriptor.Descriptor(
  name='StateMultipleResponse',
  full_name='StateMultipleResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='state', full_name='StateMultipleResponse.state', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=391,
  serialized_end=444,
)


_STATETABLERESPONSE = _descriptor.Descriptor(
  name='StateTableResponse',
  full_name='StateTableResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='items', full_name='StateTableResponse.items', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='page', full_name='StateTableResponse.page', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='per_page', full_name='StateTableResponse.per_page', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='total_items', full_name='StateTableResponse.total_items', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='num_pages', full_name='StateTableResponse.num_pages', index=4,
      number=5, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=446,
  serialized_end=568,
)

_STATENOTIDREQUEST.fields_by_name['cities'].message_type = _CITIES
_STATEREQUEST.fields_by_name['cities'].message_type = _CITIES
_STATERESPONSE.fields_by_name['state'].message_type = _STATEREQUEST
_STATEMULTIPLERESPONSE.fields_by_name['state'].message_type = _STATEREQUEST
_STATETABLERESPONSE.fields_by_name['items'].message_type = _STATEREQUEST
DESCRIPTOR.message_types_by_name['StateEmpty'] = _STATEEMPTY
DESCRIPTOR.message_types_by_name['StateIdRequest'] = _STATEIDREQUEST
DESCRIPTOR.message_types_by_name['Cities'] = _CITIES
DESCRIPTOR.message_types_by_name['StateNotIdRequest'] = _STATENOTIDREQUEST
DESCRIPTOR.message_types_by_name['StateRequest'] = _STATEREQUEST
DESCRIPTOR.message_types_by_name['StateTableRequest'] = _STATETABLEREQUEST
DESCRIPTOR.message_types_by_name['StateResponse'] = _STATERESPONSE
DESCRIPTOR.message_types_by_name['StateMultipleResponse'] = _STATEMULTIPLERESPONSE
DESCRIPTOR.message_types_by_name['StateTableResponse'] = _STATETABLERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StateEmpty = _reflection.GeneratedProtocolMessageType('StateEmpty', (_message.Message,), {
  'DESCRIPTOR' : _STATEEMPTY,
  '__module__' : 'state_pb2'
  # @@protoc_insertion_point(class_scope:StateEmpty)
  })
_sym_db.RegisterMessage(StateEmpty)

StateIdRequest = _reflection.GeneratedProtocolMessageType('StateIdRequest', (_message.Message,), {
  'DESCRIPTOR' : _STATEIDREQUEST,
  '__module__' : 'state_pb2'
  # @@protoc_insertion_point(class_scope:StateIdRequest)
  })
_sym_db.RegisterMessage(StateIdRequest)

Cities = _reflection.GeneratedProtocolMessageType('Cities', (_message.Message,), {
  'DESCRIPTOR' : _CITIES,
  '__module__' : 'state_pb2'
  # @@protoc_insertion_point(class_scope:Cities)
  })
_sym_db.RegisterMessage(Cities)

StateNotIdRequest = _reflection.GeneratedProtocolMessageType('StateNotIdRequest', (_message.Message,), {
  'DESCRIPTOR' : _STATENOTIDREQUEST,
  '__module__' : 'state_pb2'
  # @@protoc_insertion_point(class_scope:StateNotIdRequest)
  })
_sym_db.RegisterMessage(StateNotIdRequest)

StateRequest = _reflection.GeneratedProtocolMessageType('StateRequest', (_message.Message,), {
  'DESCRIPTOR' : _STATEREQUEST,
  '__module__' : 'state_pb2'
  # @@protoc_insertion_point(class_scope:StateRequest)
  })
_sym_db.RegisterMessage(StateRequest)

StateTableRequest = _reflection.GeneratedProtocolMessageType('StateTableRequest', (_message.Message,), {
  'DESCRIPTOR' : _STATETABLEREQUEST,
  '__module__' : 'state_pb2'
  # @@protoc_insertion_point(class_scope:StateTableRequest)
  })
_sym_db.RegisterMessage(StateTableRequest)

StateResponse = _reflection.GeneratedProtocolMessageType('StateResponse', (_message.Message,), {
  'DESCRIPTOR' : _STATERESPONSE,
  '__module__' : 'state_pb2'
  # @@protoc_insertion_point(class_scope:StateResponse)
  })
_sym_db.RegisterMessage(StateResponse)

StateMultipleResponse = _reflection.GeneratedProtocolMessageType('StateMultipleResponse', (_message.Message,), {
  'DESCRIPTOR' : _STATEMULTIPLERESPONSE,
  '__module__' : 'state_pb2'
  # @@protoc_insertion_point(class_scope:StateMultipleResponse)
  })
_sym_db.RegisterMessage(StateMultipleResponse)

StateTableResponse = _reflection.GeneratedProtocolMessageType('StateTableResponse', (_message.Message,), {
  'DESCRIPTOR' : _STATETABLERESPONSE,
  '__module__' : 'state_pb2'
  # @@protoc_insertion_point(class_scope:StateTableResponse)
  })
_sym_db.RegisterMessage(StateTableResponse)



_STATE = _descriptor.ServiceDescriptor(
  name='State',
  full_name='State',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=571,
  serialized_end=841,
  methods=[
  _descriptor.MethodDescriptor(
    name='table',
    full_name='State.table',
    index=0,
    containing_service=None,
    input_type=_STATETABLEREQUEST,
    output_type=_STATETABLERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='get_all',
    full_name='State.get_all',
    index=1,
    containing_service=None,
    input_type=_STATEEMPTY,
    output_type=_STATEMULTIPLERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='get',
    full_name='State.get',
    index=2,
    containing_service=None,
    input_type=_STATEIDREQUEST,
    output_type=_STATERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='save',
    full_name='State.save',
    index=3,
    containing_service=None,
    input_type=_STATENOTIDREQUEST,
    output_type=_STATERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='update',
    full_name='State.update',
    index=4,
    containing_service=None,
    input_type=_STATEREQUEST,
    output_type=_STATERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='delete',
    full_name='State.delete',
    index=5,
    containing_service=None,
    input_type=_STATEIDREQUEST,
    output_type=_STATEEMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_STATE)

DESCRIPTOR.services_by_name['State'] = _STATE

# @@protoc_insertion_point(module_scope)
