# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: websocket.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='websocket.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0fwebsocket.proto\",\n\x14SendWebsocketRequest\x12\x14\n\x06\x61\x63tive\x18\x01 \x02(\x08:\x04true\"\'\n\x15SendWebsocketResponse\x12\x0e\n\x06result\x18\x01 \x02(\t2Q\n\nWebsockets\x12\x43\n\x12\x61\x63tivate_websocket\x12\x15.SendWebsocketRequest\x1a\x16.SendWebsocketResponse'
)




_SENDWEBSOCKETREQUEST = _descriptor.Descriptor(
  name='SendWebsocketRequest',
  full_name='SendWebsocketRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='active', full_name='SendWebsocketRequest.active', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=63,
)


_SENDWEBSOCKETRESPONSE = _descriptor.Descriptor(
  name='SendWebsocketResponse',
  full_name='SendWebsocketResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='SendWebsocketResponse.result', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=65,
  serialized_end=104,
)

DESCRIPTOR.message_types_by_name['SendWebsocketRequest'] = _SENDWEBSOCKETREQUEST
DESCRIPTOR.message_types_by_name['SendWebsocketResponse'] = _SENDWEBSOCKETRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SendWebsocketRequest = _reflection.GeneratedProtocolMessageType('SendWebsocketRequest', (_message.Message,), {
  'DESCRIPTOR' : _SENDWEBSOCKETREQUEST,
  '__module__' : 'websocket_pb2'
  # @@protoc_insertion_point(class_scope:SendWebsocketRequest)
  })
_sym_db.RegisterMessage(SendWebsocketRequest)

SendWebsocketResponse = _reflection.GeneratedProtocolMessageType('SendWebsocketResponse', (_message.Message,), {
  'DESCRIPTOR' : _SENDWEBSOCKETRESPONSE,
  '__module__' : 'websocket_pb2'
  # @@protoc_insertion_point(class_scope:SendWebsocketResponse)
  })
_sym_db.RegisterMessage(SendWebsocketResponse)



_WEBSOCKETS = _descriptor.ServiceDescriptor(
  name='Websockets',
  full_name='Websockets',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=106,
  serialized_end=187,
  methods=[
  _descriptor.MethodDescriptor(
    name='activate_websocket',
    full_name='Websockets.activate_websocket',
    index=0,
    containing_service=None,
    input_type=_SENDWEBSOCKETREQUEST,
    output_type=_SENDWEBSOCKETRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_WEBSOCKETS)

DESCRIPTOR.services_by_name['Websockets'] = _WEBSOCKETS

# @@protoc_insertion_point(module_scope)
