# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import websocket_pb2 as websocket__pb2


class WebsocketsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.activate_websocket = channel.unary_unary(
                '/Websockets/activate_websocket',
                request_serializer=websocket__pb2.SendWebsocketRequest.SerializeToString,
                response_deserializer=websocket__pb2.SendWebsocketResponse.FromString,
                )


class WebsocketsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def activate_websocket(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WebsocketsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'activate_websocket': grpc.unary_unary_rpc_method_handler(
                    servicer.activate_websocket,
                    request_deserializer=websocket__pb2.SendWebsocketRequest.FromString,
                    response_serializer=websocket__pb2.SendWebsocketResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Websockets', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Websockets(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def activate_websocket(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Websockets/activate_websocket',
            websocket__pb2.SendWebsocketRequest.SerializeToString,
            websocket__pb2.SendWebsocketResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
