# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import currency_pb2 as app_dot_services_dot_currency_dot_currency__pb2


class CurrencyStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.table = channel.unary_unary(
                '/Currency/table',
                request_serializer=app_dot_services_dot_currency_dot_currency__pb2.CurrencyTableRequest.SerializeToString,
                response_deserializer=app_dot_services_dot_currency_dot_currency__pb2.CurrencyTableResponse.FromString,
                )
        self.get_all = channel.unary_unary(
                '/Currency/get_all',
                request_serializer=app_dot_services_dot_currency_dot_currency__pb2.CurrencyEmpty.SerializeToString,
                response_deserializer=app_dot_services_dot_currency_dot_currency__pb2.CurrencyMultipleResponse.FromString,
                )
        self.get = channel.unary_unary(
                '/Currency/get',
                request_serializer=app_dot_services_dot_currency_dot_currency__pb2.CurrencyIdRequest.SerializeToString,
                response_deserializer=app_dot_services_dot_currency_dot_currency__pb2.CurrencyResponse.FromString,
                )
        self.save = channel.unary_unary(
                '/Currency/save',
                request_serializer=app_dot_services_dot_currency_dot_currency__pb2.CurrencyNotIdRequest.SerializeToString,
                response_deserializer=app_dot_services_dot_currency_dot_currency__pb2.CurrencyResponse.FromString,
                )
        self.update = channel.unary_unary(
                '/Currency/update',
                request_serializer=app_dot_services_dot_currency_dot_currency__pb2.CurrencyRequest.SerializeToString,
                response_deserializer=app_dot_services_dot_currency_dot_currency__pb2.CurrencyResponse.FromString,
                )
        self.delete = channel.unary_unary(
                '/Currency/delete',
                request_serializer=app_dot_services_dot_currency_dot_currency__pb2.CurrencyIdRequest.SerializeToString,
                response_deserializer=app_dot_services_dot_currency_dot_currency__pb2.CurrencyResponse.FromString,
                )


class CurrencyServicer(object):
    """Missing associated documentation comment in .proto file."""

    def table(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_all(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def save(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CurrencyServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'table': grpc.unary_unary_rpc_method_handler(
                    servicer.table,
                    request_deserializer=app_dot_services_dot_currency_dot_currency__pb2.CurrencyTableRequest.FromString,
                    response_serializer=app_dot_services_dot_currency_dot_currency__pb2.CurrencyTableResponse.SerializeToString,
            ),
            'get_all': grpc.unary_unary_rpc_method_handler(
                    servicer.get_all,
                    request_deserializer=app_dot_services_dot_currency_dot_currency__pb2.CurrencyEmpty.FromString,
                    response_serializer=app_dot_services_dot_currency_dot_currency__pb2.CurrencyMultipleResponse.SerializeToString,
            ),
            'get': grpc.unary_unary_rpc_method_handler(
                    servicer.get,
                    request_deserializer=app_dot_services_dot_currency_dot_currency__pb2.CurrencyIdRequest.FromString,
                    response_serializer=app_dot_services_dot_currency_dot_currency__pb2.CurrencyResponse.SerializeToString,
            ),
            'save': grpc.unary_unary_rpc_method_handler(
                    servicer.save,
                    request_deserializer=app_dot_services_dot_currency_dot_currency__pb2.CurrencyNotIdRequest.FromString,
                    response_serializer=app_dot_services_dot_currency_dot_currency__pb2.CurrencyResponse.SerializeToString,
            ),
            'update': grpc.unary_unary_rpc_method_handler(
                    servicer.update,
                    request_deserializer=app_dot_services_dot_currency_dot_currency__pb2.CurrencyRequest.FromString,
                    response_serializer=app_dot_services_dot_currency_dot_currency__pb2.CurrencyResponse.SerializeToString,
            ),
            'delete': grpc.unary_unary_rpc_method_handler(
                    servicer.delete,
                    request_deserializer=app_dot_services_dot_currency_dot_currency__pb2.CurrencyIdRequest.FromString,
                    response_serializer=app_dot_services_dot_currency_dot_currency__pb2.CurrencyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Currency', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Currency(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def table(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Currency/table',
            app_dot_services_dot_currency_dot_currency__pb2.CurrencyTableRequest.SerializeToString,
            app_dot_services_dot_currency_dot_currency__pb2.CurrencyTableResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def get_all(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Currency/get_all',
            app_dot_services_dot_currency_dot_currency__pb2.CurrencyEmpty.SerializeToString,
            app_dot_services_dot_currency_dot_currency__pb2.CurrencyMultipleResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Currency/get',
            app_dot_services_dot_currency_dot_currency__pb2.CurrencyIdRequest.SerializeToString,
            app_dot_services_dot_currency_dot_currency__pb2.CurrencyResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def save(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Currency/save',
            app_dot_services_dot_currency_dot_currency__pb2.CurrencyNotIdRequest.SerializeToString,
            app_dot_services_dot_currency_dot_currency__pb2.CurrencyResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Currency/update',
            app_dot_services_dot_currency_dot_currency__pb2.CurrencyRequest.SerializeToString,
            app_dot_services_dot_currency_dot_currency__pb2.CurrencyResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Currency/delete',
            app_dot_services_dot_currency_dot_currency__pb2.CurrencyIdRequest.SerializeToString,
            app_dot_services_dot_currency_dot_currency__pb2.CurrencyResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
