# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import language_pb2 as app_dot_services_dot_language_dot_language__pb2


class LanguageStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.table = channel.unary_unary(
                '/Language/table',
                request_serializer=app_dot_services_dot_language_dot_language__pb2.LanguageTableRequest.SerializeToString,
                response_deserializer=app_dot_services_dot_language_dot_language__pb2.LanguageTableResponse.FromString,
                )
        self.get_all = channel.unary_unary(
                '/Language/get_all',
                request_serializer=app_dot_services_dot_language_dot_language__pb2.LanguageEmpty.SerializeToString,
                response_deserializer=app_dot_services_dot_language_dot_language__pb2.LanguageMultipleResponse.FromString,
                )
        self.get = channel.unary_unary(
                '/Language/get',
                request_serializer=app_dot_services_dot_language_dot_language__pb2.LanguageIdRequest.SerializeToString,
                response_deserializer=app_dot_services_dot_language_dot_language__pb2.LanguageResponse.FromString,
                )
        self.save = channel.unary_unary(
                '/Language/save',
                request_serializer=app_dot_services_dot_language_dot_language__pb2.LanguageNotIdRequest.SerializeToString,
                response_deserializer=app_dot_services_dot_language_dot_language__pb2.LanguageResponse.FromString,
                )
        self.update = channel.unary_unary(
                '/Language/update',
                request_serializer=app_dot_services_dot_language_dot_language__pb2.LanguageRequest.SerializeToString,
                response_deserializer=app_dot_services_dot_language_dot_language__pb2.LanguageResponse.FromString,
                )
        self.delete = channel.unary_unary(
                '/Language/delete',
                request_serializer=app_dot_services_dot_language_dot_language__pb2.LanguageIdRequest.SerializeToString,
                response_deserializer=app_dot_services_dot_language_dot_language__pb2.LanguageResponse.FromString,
                )


class LanguageServicer(object):
    """Missing associated documentation comment in .proto file."""

    def table(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_all(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def save(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LanguageServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'table': grpc.unary_unary_rpc_method_handler(
                    servicer.table,
                    request_deserializer=app_dot_services_dot_language_dot_language__pb2.LanguageTableRequest.FromString,
                    response_serializer=app_dot_services_dot_language_dot_language__pb2.LanguageTableResponse.SerializeToString,
            ),
            'get_all': grpc.unary_unary_rpc_method_handler(
                    servicer.get_all,
                    request_deserializer=app_dot_services_dot_language_dot_language__pb2.LanguageEmpty.FromString,
                    response_serializer=app_dot_services_dot_language_dot_language__pb2.LanguageMultipleResponse.SerializeToString,
            ),
            'get': grpc.unary_unary_rpc_method_handler(
                    servicer.get,
                    request_deserializer=app_dot_services_dot_language_dot_language__pb2.LanguageIdRequest.FromString,
                    response_serializer=app_dot_services_dot_language_dot_language__pb2.LanguageResponse.SerializeToString,
            ),
            'save': grpc.unary_unary_rpc_method_handler(
                    servicer.save,
                    request_deserializer=app_dot_services_dot_language_dot_language__pb2.LanguageNotIdRequest.FromString,
                    response_serializer=app_dot_services_dot_language_dot_language__pb2.LanguageResponse.SerializeToString,
            ),
            'update': grpc.unary_unary_rpc_method_handler(
                    servicer.update,
                    request_deserializer=app_dot_services_dot_language_dot_language__pb2.LanguageRequest.FromString,
                    response_serializer=app_dot_services_dot_language_dot_language__pb2.LanguageResponse.SerializeToString,
            ),
            'delete': grpc.unary_unary_rpc_method_handler(
                    servicer.delete,
                    request_deserializer=app_dot_services_dot_language_dot_language__pb2.LanguageIdRequest.FromString,
                    response_serializer=app_dot_services_dot_language_dot_language__pb2.LanguageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Language', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Language(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def table(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Language/table',
            app_dot_services_dot_language_dot_language__pb2.LanguageTableRequest.SerializeToString,
            app_dot_services_dot_language_dot_language__pb2.LanguageTableResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def get_all(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Language/get_all',
            app_dot_services_dot_language_dot_language__pb2.LanguageEmpty.SerializeToString,
            app_dot_services_dot_language_dot_language__pb2.LanguageMultipleResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Language/get',
            app_dot_services_dot_language_dot_language__pb2.LanguageIdRequest.SerializeToString,
            app_dot_services_dot_language_dot_language__pb2.LanguageResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def save(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Language/save',
            app_dot_services_dot_language_dot_language__pb2.LanguageNotIdRequest.SerializeToString,
            app_dot_services_dot_language_dot_language__pb2.LanguageResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Language/update',
            app_dot_services_dot_language_dot_language__pb2.LanguageRequest.SerializeToString,
            app_dot_services_dot_language_dot_language__pb2.LanguageResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Language/delete',
            app_dot_services_dot_language_dot_language__pb2.LanguageIdRequest.SerializeToString,
            app_dot_services_dot_language_dot_language__pb2.LanguageResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
