# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/services/language/language.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='app/services/language/language.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n$app/services/language/language.proto\"\x0f\n\rLanguageEmpty\"\x1f\n\x11LanguageIdRequest\x12\n\n\x02id\x18\x01 \x02(\t\"J\n\x14LanguageNotIdRequest\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x0e\n\x06prefix\x18\x02 \x02(\t\x12\x14\n\x06\x61\x63tive\x18\x03 \x01(\x08:\x04true\"Q\n\x0fLanguageRequest\x12\n\n\x02id\x18\x01 \x02(\t\x12\x0c\n\x04name\x18\x02 \x02(\t\x12\x0e\n\x06prefix\x18\x03 \x02(\t\x12\x14\n\x06\x61\x63tive\x18\x04 \x01(\x08:\x04true\"J\n\x14LanguageTableRequest\x12\x0c\n\x04page\x18\x01 \x02(\x05\x12\x14\n\x08per_page\x18\x02 \x01(\x05:\x02\x31\x35\x12\x0e\n\x06search\x18\x03 \x01(\t\"6\n\x10LanguageResponse\x12\"\n\x08language\x18\x01 \x02(\x0b\x32\x10.LanguageRequest\">\n\x18LanguageMultipleResponse\x12\"\n\x08language\x18\x01 \x03(\x0b\x32\x10.LanguageRequest\"\x80\x01\n\x15LanguageTableResponse\x12\x1f\n\x05items\x18\x01 \x03(\x0b\x32\x10.LanguageRequest\x12\x0c\n\x04page\x18\x02 \x02(\x05\x12\x10\n\x08per_page\x18\x03 \x02(\x05\x12\x13\n\x0btotal_items\x18\x04 \x02(\x05\x12\x11\n\tnum_pages\x18\x05 \x02(\x05\x32\xb8\x02\n\x08Language\x12\x36\n\x05table\x12\x15.LanguageTableRequest\x1a\x16.LanguageTableResponse\x12\x34\n\x07get_all\x12\x0e.LanguageEmpty\x1a\x19.LanguageMultipleResponse\x12,\n\x03get\x12\x12.LanguageIdRequest\x1a\x11.LanguageResponse\x12\x30\n\x04save\x12\x15.LanguageNotIdRequest\x1a\x11.LanguageResponse\x12-\n\x06update\x12\x10.LanguageRequest\x1a\x11.LanguageResponse\x12/\n\x06\x64\x65lete\x12\x12.LanguageIdRequest\x1a\x11.LanguageResponse'
)




_LANGUAGEEMPTY = _descriptor.Descriptor(
  name='LanguageEmpty',
  full_name='LanguageEmpty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=55,
)


_LANGUAGEIDREQUEST = _descriptor.Descriptor(
  name='LanguageIdRequest',
  full_name='LanguageIdRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='LanguageIdRequest.id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=57,
  serialized_end=88,
)


_LANGUAGENOTIDREQUEST = _descriptor.Descriptor(
  name='LanguageNotIdRequest',
  full_name='LanguageNotIdRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='LanguageNotIdRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='prefix', full_name='LanguageNotIdRequest.prefix', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='active', full_name='LanguageNotIdRequest.active', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=90,
  serialized_end=164,
)


_LANGUAGEREQUEST = _descriptor.Descriptor(
  name='LanguageRequest',
  full_name='LanguageRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='LanguageRequest.id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='LanguageRequest.name', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='prefix', full_name='LanguageRequest.prefix', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='active', full_name='LanguageRequest.active', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=166,
  serialized_end=247,
)


_LANGUAGETABLEREQUEST = _descriptor.Descriptor(
  name='LanguageTableRequest',
  full_name='LanguageTableRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='page', full_name='LanguageTableRequest.page', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='per_page', full_name='LanguageTableRequest.per_page', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=15,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='search', full_name='LanguageTableRequest.search', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=249,
  serialized_end=323,
)


_LANGUAGERESPONSE = _descriptor.Descriptor(
  name='LanguageResponse',
  full_name='LanguageResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='language', full_name='LanguageResponse.language', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=325,
  serialized_end=379,
)


_LANGUAGEMULTIPLERESPONSE = _descriptor.Descriptor(
  name='LanguageMultipleResponse',
  full_name='LanguageMultipleResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='language', full_name='LanguageMultipleResponse.language', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=381,
  serialized_end=443,
)


_LANGUAGETABLERESPONSE = _descriptor.Descriptor(
  name='LanguageTableResponse',
  full_name='LanguageTableResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='items', full_name='LanguageTableResponse.items', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='page', full_name='LanguageTableResponse.page', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='per_page', full_name='LanguageTableResponse.per_page', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='total_items', full_name='LanguageTableResponse.total_items', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='num_pages', full_name='LanguageTableResponse.num_pages', index=4,
      number=5, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=446,
  serialized_end=574,
)

_LANGUAGERESPONSE.fields_by_name['language'].message_type = _LANGUAGEREQUEST
_LANGUAGEMULTIPLERESPONSE.fields_by_name['language'].message_type = _LANGUAGEREQUEST
_LANGUAGETABLERESPONSE.fields_by_name['items'].message_type = _LANGUAGEREQUEST
DESCRIPTOR.message_types_by_name['LanguageEmpty'] = _LANGUAGEEMPTY
DESCRIPTOR.message_types_by_name['LanguageIdRequest'] = _LANGUAGEIDREQUEST
DESCRIPTOR.message_types_by_name['LanguageNotIdRequest'] = _LANGUAGENOTIDREQUEST
DESCRIPTOR.message_types_by_name['LanguageRequest'] = _LANGUAGEREQUEST
DESCRIPTOR.message_types_by_name['LanguageTableRequest'] = _LANGUAGETABLEREQUEST
DESCRIPTOR.message_types_by_name['LanguageResponse'] = _LANGUAGERESPONSE
DESCRIPTOR.message_types_by_name['LanguageMultipleResponse'] = _LANGUAGEMULTIPLERESPONSE
DESCRIPTOR.message_types_by_name['LanguageTableResponse'] = _LANGUAGETABLERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LanguageEmpty = _reflection.GeneratedProtocolMessageType('LanguageEmpty', (_message.Message,), {
  'DESCRIPTOR' : _LANGUAGEEMPTY,
  '__module__' : 'app.services.language.language_pb2'
  # @@protoc_insertion_point(class_scope:LanguageEmpty)
  })
_sym_db.RegisterMessage(LanguageEmpty)

LanguageIdRequest = _reflection.GeneratedProtocolMessageType('LanguageIdRequest', (_message.Message,), {
  'DESCRIPTOR' : _LANGUAGEIDREQUEST,
  '__module__' : 'app.services.language.language_pb2'
  # @@protoc_insertion_point(class_scope:LanguageIdRequest)
  })
_sym_db.RegisterMessage(LanguageIdRequest)

LanguageNotIdRequest = _reflection.GeneratedProtocolMessageType('LanguageNotIdRequest', (_message.Message,), {
  'DESCRIPTOR' : _LANGUAGENOTIDREQUEST,
  '__module__' : 'app.services.language.language_pb2'
  # @@protoc_insertion_point(class_scope:LanguageNotIdRequest)
  })
_sym_db.RegisterMessage(LanguageNotIdRequest)

LanguageRequest = _reflection.GeneratedProtocolMessageType('LanguageRequest', (_message.Message,), {
  'DESCRIPTOR' : _LANGUAGEREQUEST,
  '__module__' : 'app.services.language.language_pb2'
  # @@protoc_insertion_point(class_scope:LanguageRequest)
  })
_sym_db.RegisterMessage(LanguageRequest)

LanguageTableRequest = _reflection.GeneratedProtocolMessageType('LanguageTableRequest', (_message.Message,), {
  'DESCRIPTOR' : _LANGUAGETABLEREQUEST,
  '__module__' : 'app.services.language.language_pb2'
  # @@protoc_insertion_point(class_scope:LanguageTableRequest)
  })
_sym_db.RegisterMessage(LanguageTableRequest)

LanguageResponse = _reflection.GeneratedProtocolMessageType('LanguageResponse', (_message.Message,), {
  'DESCRIPTOR' : _LANGUAGERESPONSE,
  '__module__' : 'app.services.language.language_pb2'
  # @@protoc_insertion_point(class_scope:LanguageResponse)
  })
_sym_db.RegisterMessage(LanguageResponse)

LanguageMultipleResponse = _reflection.GeneratedProtocolMessageType('LanguageMultipleResponse', (_message.Message,), {
  'DESCRIPTOR' : _LANGUAGEMULTIPLERESPONSE,
  '__module__' : 'app.services.language.language_pb2'
  # @@protoc_insertion_point(class_scope:LanguageMultipleResponse)
  })
_sym_db.RegisterMessage(LanguageMultipleResponse)

LanguageTableResponse = _reflection.GeneratedProtocolMessageType('LanguageTableResponse', (_message.Message,), {
  'DESCRIPTOR' : _LANGUAGETABLERESPONSE,
  '__module__' : 'app.services.language.language_pb2'
  # @@protoc_insertion_point(class_scope:LanguageTableResponse)
  })
_sym_db.RegisterMessage(LanguageTableResponse)



_LANGUAGE = _descriptor.ServiceDescriptor(
  name='Language',
  full_name='Language',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=577,
  serialized_end=889,
  methods=[
  _descriptor.MethodDescriptor(
    name='table',
    full_name='Language.table',
    index=0,
    containing_service=None,
    input_type=_LANGUAGETABLEREQUEST,
    output_type=_LANGUAGETABLERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='get_all',
    full_name='Language.get_all',
    index=1,
    containing_service=None,
    input_type=_LANGUAGEEMPTY,
    output_type=_LANGUAGEMULTIPLERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='get',
    full_name='Language.get',
    index=2,
    containing_service=None,
    input_type=_LANGUAGEIDREQUEST,
    output_type=_LANGUAGERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='save',
    full_name='Language.save',
    index=3,
    containing_service=None,
    input_type=_LANGUAGENOTIDREQUEST,
    output_type=_LANGUAGERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='update',
    full_name='Language.update',
    index=4,
    containing_service=None,
    input_type=_LANGUAGEREQUEST,
    output_type=_LANGUAGERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='delete',
    full_name='Language.delete',
    index=5,
    containing_service=None,
    input_type=_LANGUAGEIDREQUEST,
    output_type=_LANGUAGERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_LANGUAGE)

DESCRIPTOR.services_by_name['Language'] = _LANGUAGE

# @@protoc_insertion_point(module_scope)
