# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import auth_pb2 as app_dot_services_dot_auth_dot_auth__pb2


class AuthStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.signup = channel.unary_unary(
                '/Auth/signup',
                request_serializer=app_dot_services_dot_auth_dot_auth__pb2.SignupRequest.SerializeToString,
                response_deserializer=app_dot_services_dot_auth_dot_auth__pb2.SignupResponse.FromString,
                )
        self.signin = channel.unary_unary(
                '/Auth/signin',
                request_serializer=app_dot_services_dot_auth_dot_auth__pb2.SigninRequest.SerializeToString,
                response_deserializer=app_dot_services_dot_auth_dot_auth__pb2.SigninResponse.FromString,
                )


class AuthServicer(object):
    """Missing associated documentation comment in .proto file."""

    def signup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def signin(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuthServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'signup': grpc.unary_unary_rpc_method_handler(
                    servicer.signup,
                    request_deserializer=app_dot_services_dot_auth_dot_auth__pb2.SignupRequest.FromString,
                    response_serializer=app_dot_services_dot_auth_dot_auth__pb2.SignupResponse.SerializeToString,
            ),
            'signin': grpc.unary_unary_rpc_method_handler(
                    servicer.signin,
                    request_deserializer=app_dot_services_dot_auth_dot_auth__pb2.SigninRequest.FromString,
                    response_serializer=app_dot_services_dot_auth_dot_auth__pb2.SigninResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Auth', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Auth(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def signup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Auth/signup',
            app_dot_services_dot_auth_dot_auth__pb2.SignupRequest.SerializeToString,
            app_dot_services_dot_auth_dot_auth__pb2.SignupResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def signin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Auth/signin',
            app_dot_services_dot_auth_dot_auth__pb2.SigninRequest.SerializeToString,
            app_dot_services_dot_auth_dot_auth__pb2.SigninResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
