# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import role_pb2 as app_dot_services_dot_role_dot_role__pb2


class RoleStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.table = channel.unary_unary(
                '/Role/table',
                request_serializer=app_dot_services_dot_role_dot_role__pb2.RoleTableRequest.SerializeToString,
                response_deserializer=app_dot_services_dot_role_dot_role__pb2.RoleTableResponse.FromString,
                )
        self.get_all = channel.unary_unary(
                '/Role/get_all',
                request_serializer=app_dot_services_dot_role_dot_role__pb2.RoleEmpty.SerializeToString,
                response_deserializer=app_dot_services_dot_role_dot_role__pb2.RoleMultipleResponse.FromString,
                )
        self.get = channel.unary_unary(
                '/Role/get',
                request_serializer=app_dot_services_dot_role_dot_role__pb2.RoleIdRequest.SerializeToString,
                response_deserializer=app_dot_services_dot_role_dot_role__pb2.RoleResponse.FromString,
                )
        self.save = channel.unary_unary(
                '/Role/save',
                request_serializer=app_dot_services_dot_role_dot_role__pb2.RoleNotIdRequest.SerializeToString,
                response_deserializer=app_dot_services_dot_role_dot_role__pb2.RoleResponse.FromString,
                )
        self.update = channel.unary_unary(
                '/Role/update',
                request_serializer=app_dot_services_dot_role_dot_role__pb2.RoleRequest.SerializeToString,
                response_deserializer=app_dot_services_dot_role_dot_role__pb2.RoleResponse.FromString,
                )
        self.delete = channel.unary_unary(
                '/Role/delete',
                request_serializer=app_dot_services_dot_role_dot_role__pb2.RoleIdRequest.SerializeToString,
                response_deserializer=app_dot_services_dot_role_dot_role__pb2.RoleResponse.FromString,
                )


class RoleServicer(object):
    """Missing associated documentation comment in .proto file."""

    def table(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_all(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def save(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RoleServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'table': grpc.unary_unary_rpc_method_handler(
                    servicer.table,
                    request_deserializer=app_dot_services_dot_role_dot_role__pb2.RoleTableRequest.FromString,
                    response_serializer=app_dot_services_dot_role_dot_role__pb2.RoleTableResponse.SerializeToString,
            ),
            'get_all': grpc.unary_unary_rpc_method_handler(
                    servicer.get_all,
                    request_deserializer=app_dot_services_dot_role_dot_role__pb2.RoleEmpty.FromString,
                    response_serializer=app_dot_services_dot_role_dot_role__pb2.RoleMultipleResponse.SerializeToString,
            ),
            'get': grpc.unary_unary_rpc_method_handler(
                    servicer.get,
                    request_deserializer=app_dot_services_dot_role_dot_role__pb2.RoleIdRequest.FromString,
                    response_serializer=app_dot_services_dot_role_dot_role__pb2.RoleResponse.SerializeToString,
            ),
            'save': grpc.unary_unary_rpc_method_handler(
                    servicer.save,
                    request_deserializer=app_dot_services_dot_role_dot_role__pb2.RoleNotIdRequest.FromString,
                    response_serializer=app_dot_services_dot_role_dot_role__pb2.RoleResponse.SerializeToString,
            ),
            'update': grpc.unary_unary_rpc_method_handler(
                    servicer.update,
                    request_deserializer=app_dot_services_dot_role_dot_role__pb2.RoleRequest.FromString,
                    response_serializer=app_dot_services_dot_role_dot_role__pb2.RoleResponse.SerializeToString,
            ),
            'delete': grpc.unary_unary_rpc_method_handler(
                    servicer.delete,
                    request_deserializer=app_dot_services_dot_role_dot_role__pb2.RoleIdRequest.FromString,
                    response_serializer=app_dot_services_dot_role_dot_role__pb2.RoleResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Role', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Role(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def table(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Role/table',
            app_dot_services_dot_role_dot_role__pb2.RoleTableRequest.SerializeToString,
            app_dot_services_dot_role_dot_role__pb2.RoleTableResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def get_all(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Role/get_all',
            app_dot_services_dot_role_dot_role__pb2.RoleEmpty.SerializeToString,
            app_dot_services_dot_role_dot_role__pb2.RoleMultipleResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Role/get',
            app_dot_services_dot_role_dot_role__pb2.RoleIdRequest.SerializeToString,
            app_dot_services_dot_role_dot_role__pb2.RoleResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def save(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Role/save',
            app_dot_services_dot_role_dot_role__pb2.RoleNotIdRequest.SerializeToString,
            app_dot_services_dot_role_dot_role__pb2.RoleResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Role/update',
            app_dot_services_dot_role_dot_role__pb2.RoleRequest.SerializeToString,
            app_dot_services_dot_role_dot_role__pb2.RoleResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Role/delete',
            app_dot_services_dot_role_dot_role__pb2.RoleIdRequest.SerializeToString,
            app_dot_services_dot_role_dot_role__pb2.RoleResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
